export const remediationBrief = {
  "demo": "cvpr-remediation-release-brief",
  "status": "release",
  "commandStatus": "operator-ready",
  "ledgerStatus": "complete",
  "surfaces": 7,
  "readySurfaces": 7,
  "stages": 7,
  "readyStages": 7,
  "gauntletRows": 32,
  "gauntletBlocks": 14,
  "actionableRows": 29,
  "clearedBlocks": 14,
  "postBlock": 0,
  "promote": 12,
  "monitor": 17,
  "canaryClean": 12,
  "canaryWatch": 17,
  "canaryRollback": 0,
  "rollbackDrills": 12,
  "readyDrills": 12,
  "rehearsals": 12,
  "rehearsalMisses": 0,
  "themes": 8,
  "incidents": 4,
  "packageTests": 148,
  "fullStackStatus": "valid",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py",
  "gate": "release",
  "posture": "controlled-watch",
  "outcome": "14 gauntlet blocks \u00b7 14 cleared \u00b7 12 promote \u00b7 17 monitor \u00b7 12 rollback drills"
};
export const closeoutRows = [
  {
    "id": "closeout-01-brief",
    "label": "Remediation release brief",
    "ownerSurface": "cvpr-remediation-release-brief.html",
    "actual": "release",
    "expected": "release",
    "evidence": "analysis/cvpr_remediation_release_brief/registry.json",
    "verifyCommand": "python3 scripts/verify_cvpr_remediation_release_brief.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  },
  {
    "id": "closeout-02-command",
    "label": "Remediation command center",
    "ownerSurface": "cvpr-remediation-command-center.html",
    "actual": "operator-ready",
    "expected": "operator-ready",
    "evidence": "analysis/cvpr_remediation_command_center/registry.json",
    "verifyCommand": "python3 scripts/verify_cvpr_remediation_command_center.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  },
  {
    "id": "closeout-03-ledger",
    "label": "Remediation audit ledger",
    "ownerSurface": "cvpr-remediation-audit-ledger.html",
    "actual": "complete",
    "expected": "complete",
    "evidence": "analysis/cvpr_remediation_audit_ledger/registry.json",
    "verifyCommand": "python3 scripts/verify_cvpr_remediation_audit_ledger.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  },
  {
    "id": "closeout-04-canary",
    "label": "Remediation canary monitor",
    "ownerSurface": "cvpr-remediation-canary-monitor.html",
    "actual": "watching",
    "expected": "watching",
    "evidence": "analysis/cvpr_remediation_canary_monitor/registry.json",
    "verifyCommand": "python3 scripts/verify_cvpr_remediation_canary_monitor.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  },
  {
    "id": "closeout-05-rollback",
    "label": "Remediation rollback drillbook",
    "ownerSurface": "cvpr-remediation-rollback-drillbook.html",
    "actual": "ready",
    "expected": "ready",
    "evidence": "analysis/cvpr_remediation_rollback_drillbook/registry.json",
    "verifyCommand": "python3 scripts/verify_cvpr_remediation_rollback_drillbook.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  },
  {
    "id": "closeout-06-rehearsal",
    "label": "Remediation rollback rehearsal lab",
    "ownerSurface": "cvpr-remediation-rollback-rehearsal-lab.html",
    "actual": "release",
    "expected": "release",
    "evidence": "analysis/cvpr_remediation_rollback_rehearsal_lab/registry.json",
    "verifyCommand": "python3 scripts/verify_cvpr_remediation_rollback_rehearsal_lab.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  },
  {
    "id": "closeout-07-validation",
    "label": "Full-stack validation",
    "ownerSurface": "cvpr-validation-center.html",
    "actual": "valid",
    "expected": "valid",
    "evidence": "analysis/cvpr_full_stack_validation/registry.json",
    "verifyCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "closeoutCommand": "python3 scripts/validate_cvpr_full_stack.py",
    "changePolicy": "verify owner, rerun full stack, keep remediation release brief sealed",
    "status": "sealed"
  }
];
export const summary = {
  "demo": "cvpr-remediation-closeout-pack",
  "status": "sealed",
  "rows": 7,
  "readyRows": 7,
  "releaseGate": "release",
  "posture": "controlled-watch",
  "postBlock": 0,
  "canaryRollback": 0,
  "rehearsalMisses": 0,
  "promote": 12,
  "monitor": 17,
  "rollbackDrills": 12,
  "packageTests": 148,
  "fullStackStatus": "valid",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
