export const summary = {
  "demo": "cvpr-remediation-release-brief",
  "status": "release",
  "commandStatus": "block",
  "ledgerStatus": "inspect",
  "surfaces": 7,
  "readySurfaces": 5,
  "stages": 7,
  "readyStages": 5,
  "gauntletRows": 56,
  "gauntletBlocks": 23,
  "actionableRows": 53,
  "clearedBlocks": 23,
  "postBlock": 0,
  "promote": 18,
  "monitor": 35,
  "canaryClean": 18,
  "canaryWatch": 35,
  "canaryRollback": 0,
  "rollbackDrills": 12,
  "readyDrills": 12,
  "rehearsals": 12,
  "rehearsalMisses": 0,
  "themes": 8,
  "incidents": 7,
  "packageTests": 148,
  "fullStackStatus": "valid",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py",
  "gate": "block",
  "posture": "review",
  "outcome": "23 gauntlet blocks \u00b7 23 cleared \u00b7 18 promote \u00b7 35 monitor \u00b7 12 rollback drills"
};
