export const summary = {
  "demo": "cvpr-remediation-release-brief",
  "status": "release",
  "commandStatus": "operator-ready",
  "ledgerStatus": "complete",
  "surfaces": 7,
  "readySurfaces": 7,
  "stages": 7,
  "readyStages": 7,
  "gauntletRows": 32,
  "gauntletBlocks": 14,
  "actionableRows": 29,
  "clearedBlocks": 14,
  "postBlock": 0,
  "promote": 12,
  "monitor": 17,
  "canaryClean": 12,
  "canaryWatch": 17,
  "canaryRollback": 0,
  "rollbackDrills": 12,
  "readyDrills": 12,
  "rehearsals": 12,
  "rehearsalMisses": 0,
  "themes": 8,
  "incidents": 4,
  "packageTests": 148,
  "fullStackStatus": "valid",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py",
  "gate": "release",
  "posture": "controlled-watch",
  "outcome": "14 gauntlet blocks \u00b7 14 cleared \u00b7 12 promote \u00b7 17 monitor \u00b7 12 rollback drills"
};
