export const stages = [
  {
    "system": "video-world-model",
    "systemTitle": "Video world model",
    "stage": "temporal-memory",
    "stageTitle": "Keep temporal memory",
    "theme": "Seeing and making things that move",
    "themeSlug": "video",
    "cluster": "Video generation and world models",
    "clusterSlug": "video_world",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "carry identity and state across long sequences",
    "reusableRule": "Video world model stage 'Keep temporal memory' should carry identity and state across long sequences using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "video-world-model",
    "systemTitle": "Video world model",
    "stage": "physics-consistency",
    "stageTitle": "Check physics consistency",
    "theme": "Seeing and making things that move",
    "themeSlug": "video",
    "cluster": "Video generation and world models",
    "clusterSlug": "video_world",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "penalize impossible motion and contact",
    "reusableRule": "Video world model stage 'Check physics consistency' should penalize impossible motion and contact using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "video-world-model",
    "systemTitle": "Video world model",
    "stage": "future-rollout",
    "stageTitle": "Score future rollouts",
    "theme": "Seeing and making things that move",
    "themeSlug": "video",
    "cluster": "Video generation and world models",
    "clusterSlug": "video_world",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "separate plausible samples from useful predictions",
    "reusableRule": "Video world model stage 'Score future rollouts' should separate plausible samples from useful predictions using measured CVPR evidence, not only paper novelty."
  }
];
