export const stages = [
  {
    "system": "efficient-vision-serving",
    "systemTitle": "Efficient vision serving",
    "stage": "token-budget",
    "stageTitle": "Control token budget",
    "theme": "Learning more from less, and not breaking",
    "themeSlug": "learning",
    "cluster": "Efficient vision",
    "clusterSlug": "efficient",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "remove redundant visual tokens under a quality floor",
    "reusableRule": "Efficient vision serving stage 'Control token budget' should remove redundant visual tokens under a quality floor using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "efficient-vision-serving",
    "systemTitle": "Efficient vision serving",
    "stage": "quantized-serving",
    "stageTitle": "Serve quantized models",
    "theme": "Learning more from less, and not breaking",
    "themeSlug": "learning",
    "cluster": "Efficient vision",
    "clusterSlug": "efficient",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "use low precision only when calibration survives",
    "reusableRule": "Efficient vision serving stage 'Serve quantized models' should use low precision only when calibration survives using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "efficient-vision-serving",
    "systemTitle": "Efficient vision serving",
    "stage": "student-routing",
    "stageTitle": "Route to small students",
    "theme": "Learning more from less, and not breaking",
    "themeSlug": "learning",
    "cluster": "Efficient vision",
    "clusterSlug": "efficient",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "send easy cases to cheaper models and escalate hard cases",
    "reusableRule": "Efficient vision serving stage 'Route to small students' should send easy cases to cheaper models and escalate hard cases using measured CVPR evidence, not only paper novelty."
  }
];
