export const demos = [
  {
    "slug": "open-vocab-grounding",
    "kind": "flagship",
    "theme": "Perception",
    "cluster": "Open-vocabulary vision",
    "title": "Open-vocabulary region grounding",
    "label": "query specificity",
    "value": 72,
    "mode": "localization",
    "visualMode": "localization",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "A text query becomes usable only when confidence and localization agree."
  },
  {
    "slug": "metric-depth-uncertainty",
    "kind": "flagship",
    "theme": "3D",
    "cluster": "3D reconstruction and novel views",
    "title": "Metric depth uncertainty",
    "label": "camera baseline",
    "value": 46,
    "mode": "geometry",
    "visualMode": "geometry",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "Depth becomes reliable when parallax is strong enough to beat scale ambiguity."
  },
  {
    "slug": "temporal-world-rollout",
    "kind": "flagship",
    "theme": "Video",
    "cluster": "Video generation and world models",
    "title": "Temporal consistency rollout",
    "label": "temporal memory",
    "value": 64,
    "mode": "temporal",
    "visualMode": "temporal",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "A world model is useful only if identity drift stays below the rollout horizon."
  },
  {
    "slug": "controlled-editing",
    "kind": "flagship",
    "theme": "Generation",
    "cluster": "Controllable generation",
    "title": "Controllable editing preservation",
    "label": "edit strength",
    "value": 42,
    "mode": "editing",
    "visualMode": "editing",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "An edit succeeds when the requested change rises faster than identity damage."
  },
  {
    "slug": "vlm-grounding-check",
    "kind": "flagship",
    "theme": "VLM",
    "cluster": "Vision-language reasoning",
    "title": "Grounded reasoning vs hallucination",
    "label": "visual evidence",
    "value": 68,
    "mode": "grounding",
    "visualMode": "grounding",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "Reasoning must be gated by visible evidence before language priors dominate."
  },
  {
    "slug": "driving-action-gate",
    "kind": "flagship",
    "theme": "Embodied",
    "cluster": "Driving and vision-language-action",
    "title": "Driving VLA action gate",
    "label": "risk tolerance",
    "value": 12,
    "mode": "safety",
    "visualMode": "safety",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "A vision-language action is only released after scene grounding and risk pass."
  },
  {
    "slug": "efficient-token-serving",
    "kind": "flagship",
    "theme": "Learning",
    "cluster": "Efficient vision",
    "title": "Token pruning and serving tradeoff",
    "label": "tokens kept",
    "value": 58,
    "mode": "efficiency",
    "visualMode": "efficiency",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "Efficiency is deployable only while the retained tokens preserve task evidence."
  },
  {
    "slug": "provenance-attack-gate",
    "kind": "flagship",
    "theme": "Frontier and trust",
    "cluster": "Adversarial robustness",
    "title": "Provenance and adversarial gate",
    "label": "attack strength",
    "value": 28,
    "mode": "trust",
    "visualMode": "trust",
    "system": "cvpr-demo-lab",
    "sourceStage": null,
    "rule": "Trust requires detecting synthetic origin, edits, and adversarial perturbations."
  },
  {
    "slug": "stage-open-vocab-visual-search-text-query-grounding",
    "kind": "stage",
    "theme": "Naming and locating what's in the picture",
    "cluster": "Open-vocabulary vision",
    "title": "Ground text queries in visible regions",
    "label": "text query grounding",
    "value": 94,
    "mode": "stage",
    "visualMode": "localization",
    "system": "open-vocab-visual-search",
    "sourceStage": "text-query-grounding",
    "sourcePage": "open-vocab-visual-search.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Open-vocabulary visual search stage 'Ground text queries in visible regions' should reject answers without localized evidence using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-open-vocab-visual-search-long-tail-retrieval",
    "kind": "stage",
    "theme": "Naming and locating what's in the picture",
    "cluster": "Open-vocabulary vision",
    "title": "Retrieve long-tail objects",
    "label": "long tail retrieval",
    "value": 94,
    "mode": "stage",
    "visualMode": "localization",
    "system": "open-vocab-visual-search",
    "sourceStage": "long-tail-retrieval",
    "sourcePage": "open-vocab-visual-search.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Open-vocabulary visual search stage 'Retrieve long-tail objects' should rank rare concepts without collapsing to frequent labels using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-open-vocab-visual-search-evidence-inspection",
    "kind": "stage",
    "theme": "Naming and locating what's in the picture",
    "cluster": "Open-vocabulary vision",
    "title": "Expose search evidence",
    "label": "evidence inspection",
    "value": 94,
    "mode": "stage",
    "visualMode": "localization",
    "system": "open-vocab-visual-search",
    "sourceStage": "evidence-inspection",
    "sourcePage": "open-vocab-visual-search.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Open-vocabulary visual search stage 'Expose search evidence' should show regions, uncertainty, and failure modes before trust using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-vlm-grounded-reasoning-look-then-reason",
    "kind": "stage",
    "theme": "Teaching machines to see and talk at once",
    "cluster": "Vision-language reasoning",
    "title": "Look before reasoning",
    "label": "look then reason",
    "value": 94,
    "mode": "stage",
    "visualMode": "grounding",
    "system": "vlm-grounded-reasoning",
    "sourceStage": "look-then-reason",
    "sourcePage": "vlm-grounded-reasoning.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "VLM grounded reasoning stage 'Look before reasoning' should force answers to cite visual evidence using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-vlm-grounded-reasoning-hallucination-check",
    "kind": "stage",
    "theme": "Teaching machines to see and talk at once",
    "cluster": "Vision-language reasoning",
    "title": "Check hallucinated claims",
    "label": "hallucination check",
    "value": 94,
    "mode": "stage",
    "visualMode": "grounding",
    "system": "vlm-grounded-reasoning",
    "sourceStage": "hallucination-check",
    "sourcePage": "vlm-grounded-reasoning.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "VLM grounded reasoning stage 'Check hallucinated claims' should down-rank unsupported objects, counts, and relations using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-vlm-grounded-reasoning-tool-verified-answer",
    "kind": "stage",
    "theme": "Teaching machines to see and talk at once",
    "cluster": "Vision-language reasoning",
    "title": "Verify with visual tools",
    "label": "tool verified answer",
    "value": 94,
    "mode": "stage",
    "visualMode": "grounding",
    "system": "vlm-grounded-reasoning",
    "sourceStage": "tool-verified-answer",
    "sourcePage": "vlm-grounded-reasoning.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "VLM grounded reasoning stage 'Verify with visual tools' should route hard questions through detectors, OCR, or geometry using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-efficient-vision-serving-token-budget",
    "kind": "stage",
    "theme": "Learning more from less, and not breaking",
    "cluster": "Efficient vision",
    "title": "Control token budget",
    "label": "token budget",
    "value": 94,
    "mode": "stage",
    "visualMode": "efficiency",
    "system": "efficient-vision-serving",
    "sourceStage": "token-budget",
    "sourcePage": "efficient-vision-serving.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Efficient vision serving stage 'Control token budget' should remove redundant visual tokens under a quality floor using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-efficient-vision-serving-quantized-serving",
    "kind": "stage",
    "theme": "Learning more from less, and not breaking",
    "cluster": "Efficient vision",
    "title": "Serve quantized models",
    "label": "quantized serving",
    "value": 94,
    "mode": "stage",
    "visualMode": "efficiency",
    "system": "efficient-vision-serving",
    "sourceStage": "quantized-serving",
    "sourcePage": "efficient-vision-serving.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Efficient vision serving stage 'Serve quantized models' should use low precision only when calibration survives using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-efficient-vision-serving-student-routing",
    "kind": "stage",
    "theme": "Learning more from less, and not breaking",
    "cluster": "Efficient vision",
    "title": "Route to small students",
    "label": "student routing",
    "value": 94,
    "mode": "stage",
    "visualMode": "efficiency",
    "system": "efficient-vision-serving",
    "sourceStage": "student-routing",
    "sourcePage": "efficient-vision-serving.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Efficient vision serving stage 'Route to small students' should send easy cases to cheaper models and escalate hard cases using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-metric-3d-reconstruction-camera-geometry",
    "kind": "stage",
    "theme": "Recovering the 3D world from flat pictures",
    "cluster": "3D reconstruction and novel views",
    "title": "Recover camera geometry",
    "label": "camera geometry",
    "value": 94,
    "mode": "stage",
    "visualMode": "geometry",
    "system": "metric-3d-reconstruction",
    "sourceStage": "camera-geometry",
    "sourcePage": "metric-3d-reconstruction.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Metric 3D reconstruction pipeline stage 'Recover camera geometry' should reject reconstructions with weak pose evidence using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-metric-3d-reconstruction-metric-scale",
    "kind": "stage",
    "theme": "Recovering the 3D world from flat pictures",
    "cluster": "3D reconstruction and novel views",
    "title": "Recover metric scale",
    "label": "metric scale",
    "value": 94,
    "mode": "stage",
    "visualMode": "geometry",
    "system": "metric-3d-reconstruction",
    "sourceStage": "metric-scale",
    "sourcePage": "metric-3d-reconstruction.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Metric 3D reconstruction pipeline stage 'Recover metric scale' should pin shape to meters before downstream use using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-metric-3d-reconstruction-surface-consistency",
    "kind": "stage",
    "theme": "Recovering the 3D world from flat pictures",
    "cluster": "3D reconstruction and novel views",
    "title": "Check surface consistency",
    "label": "surface consistency",
    "value": 94,
    "mode": "stage",
    "visualMode": "geometry",
    "system": "metric-3d-reconstruction",
    "sourceStage": "surface-consistency",
    "sourcePage": "metric-3d-reconstruction.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Metric 3D reconstruction pipeline stage 'Check surface consistency' should detect holes, drift, and impossible topology using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-gaussian-splatting-platform-splat-fit",
    "kind": "stage",
    "theme": "Recovering the 3D world from flat pictures",
    "cluster": "Gaussian Splatting",
    "title": "Fit renderable splats",
    "label": "splat fit",
    "value": 94,
    "mode": "stage",
    "visualMode": "splats",
    "system": "gaussian-splatting-platform",
    "sourceStage": "splat-fit",
    "sourcePage": "gaussian-splatting-platform.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Gaussian Splatting platform stage 'Fit renderable splats' should optimize scene storage for fast novel views using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-gaussian-splatting-platform-semantic-splats",
    "kind": "stage",
    "theme": "Recovering the 3D world from flat pictures",
    "cluster": "Gaussian Splatting",
    "title": "Attach semantic labels",
    "label": "semantic splats",
    "value": 94,
    "mode": "stage",
    "visualMode": "splats",
    "system": "gaussian-splatting-platform",
    "sourceStage": "semantic-splats",
    "sourcePage": "gaussian-splatting-platform.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Gaussian Splatting platform stage 'Attach semantic labels' should make splats searchable and editable by meaning using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-gaussian-splatting-platform-watermark-provenance",
    "kind": "stage",
    "theme": "Recovering the 3D world from flat pictures",
    "cluster": "Gaussian Splatting",
    "title": "Track provenance",
    "label": "watermark provenance",
    "value": 94,
    "mode": "stage",
    "visualMode": "splats",
    "system": "gaussian-splatting-platform",
    "sourceStage": "watermark-provenance",
    "sourcePage": "gaussian-splatting-platform.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Gaussian Splatting platform stage 'Track provenance' should protect generated 3D assets with inspectable marks using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-video-world-model-temporal-memory",
    "kind": "stage",
    "theme": "Seeing and making things that move",
    "cluster": "Video generation and world models",
    "title": "Keep temporal memory",
    "label": "temporal memory",
    "value": 94,
    "mode": "stage",
    "visualMode": "temporal",
    "system": "video-world-model",
    "sourceStage": "temporal-memory",
    "sourcePage": "video-world-model.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Video world model stage 'Keep temporal memory' should carry identity and state across long sequences using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-video-world-model-physics-consistency",
    "kind": "stage",
    "theme": "Seeing and making things that move",
    "cluster": "Video generation and world models",
    "title": "Check physics consistency",
    "label": "physics consistency",
    "value": 94,
    "mode": "stage",
    "visualMode": "temporal",
    "system": "video-world-model",
    "sourceStage": "physics-consistency",
    "sourcePage": "video-world-model.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Video world model stage 'Check physics consistency' should penalize impossible motion and contact using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-video-world-model-future-rollout",
    "kind": "stage",
    "theme": "Seeing and making things that move",
    "cluster": "Video generation and world models",
    "title": "Score future rollouts",
    "label": "future rollout",
    "value": 94,
    "mode": "stage",
    "visualMode": "temporal",
    "system": "video-world-model",
    "sourceStage": "future-rollout",
    "sourcePage": "video-world-model.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Video world model stage 'Score future rollouts' should separate plausible samples from useful predictions using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-controllable-generation-studio-layout-control",
    "kind": "stage",
    "theme": "Making pixels from meaning",
    "cluster": "Controllable generation",
    "title": "Control layout",
    "label": "layout control",
    "value": 94,
    "mode": "stage",
    "visualMode": "editing",
    "system": "controllable-generation-studio",
    "sourceStage": "layout-control",
    "sourcePage": "controllable-generation-studio.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Controllable generation studio stage 'Control layout' should bind generated regions to explicit user constraints using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-controllable-generation-studio-identity-preservation",
    "kind": "stage",
    "theme": "Making pixels from meaning",
    "cluster": "Controllable generation",
    "title": "Preserve identity",
    "label": "identity preservation",
    "value": 94,
    "mode": "stage",
    "visualMode": "editing",
    "system": "controllable-generation-studio",
    "sourceStage": "identity-preservation",
    "sourcePage": "controllable-generation-studio.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Controllable generation studio stage 'Preserve identity' should measure what stayed fixed after an edit using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-controllable-generation-studio-preference-reward",
    "kind": "stage",
    "theme": "Making pixels from meaning",
    "cluster": "Controllable generation",
    "title": "Optimize preference reward",
    "label": "preference reward",
    "value": 94,
    "mode": "stage",
    "visualMode": "editing",
    "system": "controllable-generation-studio",
    "sourceStage": "preference-reward",
    "sourcePage": "controllable-generation-studio.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Controllable generation studio stage 'Optimize preference reward' should use reward only when it improves grounded constraints using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-restoration-reliability-stack-degradation-diagnosis",
    "kind": "stage",
    "theme": "Making pixels from meaning",
    "cluster": "Image restoration",
    "title": "Diagnose degradation",
    "label": "degradation diagnosis",
    "value": 94,
    "mode": "stage",
    "visualMode": "restoration",
    "system": "restoration-reliability-stack",
    "sourceStage": "degradation-diagnosis",
    "sourcePage": "restoration-reliability-stack.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Restoration reliability stack stage 'Diagnose degradation' should separate blur, noise, compression, low light, and sensor artifacts using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-restoration-reliability-stack-fidelity-gate",
    "kind": "stage",
    "theme": "Making pixels from meaning",
    "cluster": "Image restoration",
    "title": "Gate restoration fidelity",
    "label": "fidelity gate",
    "value": 94,
    "mode": "stage",
    "visualMode": "restoration",
    "system": "restoration-reliability-stack",
    "sourceStage": "fidelity-gate",
    "sourcePage": "restoration-reliability-stack.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Restoration reliability stack stage 'Gate restoration fidelity' should restore visible evidence without fabricating task-critical details using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-restoration-reliability-stack-downstream-validation",
    "kind": "stage",
    "theme": "Making pixels from meaning",
    "cluster": "Image restoration",
    "title": "Validate downstream utility",
    "label": "downstream validation",
    "value": 94,
    "mode": "stage",
    "visualMode": "restoration",
    "system": "restoration-reliability-stack",
    "sourceStage": "downstream-validation",
    "sourcePage": "restoration-reliability-stack.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Restoration reliability stack stage 'Validate downstream utility' should prove restored images improve the target task, not just aesthetics using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-medical-vision-validation-domain-shift",
    "kind": "stage",
    "theme": "The frontier - new senses and new duties",
    "cluster": "Vision for science and medicine",
    "title": "Measure domain shift",
    "label": "domain shift",
    "value": 94,
    "mode": "stage",
    "visualMode": "medical",
    "system": "medical-vision-validation",
    "sourceStage": "domain-shift",
    "sourcePage": "medical-vision-validation.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Medical vision validation stage 'Measure domain shift' should test scanners, sites, staining, and patient mix separately using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-medical-vision-validation-uncertainty-triage",
    "kind": "stage",
    "theme": "The frontier - new senses and new duties",
    "cluster": "Vision for science and medicine",
    "title": "Triage uncertainty",
    "label": "uncertainty triage",
    "value": 94,
    "mode": "stage",
    "visualMode": "medical",
    "system": "medical-vision-validation",
    "sourceStage": "uncertainty-triage",
    "sourcePage": "medical-vision-validation.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Medical vision validation stage 'Triage uncertainty' should route low-confidence cases to review using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-medical-vision-validation-clinical-evidence",
    "kind": "stage",
    "theme": "The frontier - new senses and new duties",
    "cluster": "Vision for science and medicine",
    "title": "Build clinical evidence",
    "label": "clinical evidence",
    "value": 94,
    "mode": "stage",
    "visualMode": "medical",
    "system": "medical-vision-validation",
    "sourceStage": "clinical-evidence",
    "sourcePage": "medical-vision-validation.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Medical vision validation stage 'Build clinical evidence' should require task-specific validation before deployment using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-driving-vla-release-gate-scene-grounding",
    "kind": "stage",
    "theme": "Using vision to act in the world",
    "cluster": "Driving and vision-language-action",
    "title": "Ground the driving scene",
    "label": "scene grounding",
    "value": 94,
    "mode": "stage",
    "visualMode": "safety",
    "system": "driving-vla-release-gate",
    "sourceStage": "scene-grounding",
    "sourcePage": "driving-vla-release-gate.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Driving VLA release gate stage 'Ground the driving scene' should bind actions to lanes, actors, signs, and free space using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-driving-vla-release-gate-risk-anticipation",
    "kind": "stage",
    "theme": "Using vision to act in the world",
    "cluster": "Driving and vision-language-action",
    "title": "Anticipate risk",
    "label": "risk anticipation",
    "value": 94,
    "mode": "stage",
    "visualMode": "safety",
    "system": "driving-vla-release-gate",
    "sourceStage": "risk-anticipation",
    "sourcePage": "driving-vla-release-gate.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Driving VLA release gate stage 'Anticipate risk' should score future collision and rule-violation risk using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-driving-vla-release-gate-action-release",
    "kind": "stage",
    "theme": "Using vision to act in the world",
    "cluster": "Driving and vision-language-action",
    "title": "Gate action release",
    "label": "action release",
    "value": 94,
    "mode": "stage",
    "visualMode": "safety",
    "system": "driving-vla-release-gate",
    "sourceStage": "action-release",
    "sourcePage": "driving-vla-release-gate.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Driving VLA release gate stage 'Gate action release' should execute only actions that pass perception and dynamics checks using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-adversarial-provenance-gate-attack-surface",
    "kind": "stage",
    "theme": "The frontier - new senses and new duties",
    "cluster": "Adversarial robustness",
    "title": "Map attack surface",
    "label": "attack surface",
    "value": 94,
    "mode": "stage",
    "visualMode": "trust",
    "system": "adversarial-provenance-gate",
    "sourceStage": "attack-surface",
    "sourcePage": "adversarial-provenance-gate.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Adversarial provenance gate stage 'Map attack surface' should test corruptions, prompts, generated media, and sensor shifts using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-adversarial-provenance-gate-provenance-detection",
    "kind": "stage",
    "theme": "The frontier - new senses and new duties",
    "cluster": "Adversarial robustness",
    "title": "Detect provenance",
    "label": "provenance detection",
    "value": 94,
    "mode": "stage",
    "visualMode": "trust",
    "system": "adversarial-provenance-gate",
    "sourceStage": "provenance-detection",
    "sourcePage": "adversarial-provenance-gate.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Adversarial provenance gate stage 'Detect provenance' should separate real, edited, generated, and watermarked media using measured CVPR evidence, not only paper novelty."
  },
  {
    "slug": "stage-adversarial-provenance-gate-unlearning-check",
    "kind": "stage",
    "theme": "The frontier - new senses and new duties",
    "cluster": "Adversarial robustness",
    "title": "Check unlearning",
    "label": "unlearning check",
    "value": 94,
    "mode": "stage",
    "visualMode": "trust",
    "system": "adversarial-provenance-gate",
    "sourceStage": "unlearning-check",
    "sourcePage": "adversarial-provenance-gate.html",
    "baseScore": 94,
    "baseRisk": 10,
    "evidenceDepth": 94,
    "rule": "Adversarial provenance gate stage 'Check unlearning' should prove removed concepts do not leak back through shortcuts using measured CVPR evidence, not only paper novelty."
  }
];
