export const portfolioInput = {
  "systems": {
    "summary": {
      "systems": 11,
      "stages": 33,
      "themesCovered": 8,
      "totalThemes": 8,
      "clustersCovered": 11,
      "totalClusters": 11,
      "openClusters": [],
      "complete": 33,
      "incomplete": 0
    },
    "records": [
      {
        "id": "open-vocab-visual-search/text-query-grounding",
        "system": "open-vocab-visual-search",
        "stage": "text-query-grounding",
        "theme": "Naming and locating what's in the picture",
        "cluster": "Open-vocabulary vision",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/_results/text-query-grounding.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/tests/core.test.js",
        "page": "open-vocab-visual-search.html",
        "status": "complete"
      },
      {
        "id": "open-vocab-visual-search/long-tail-retrieval",
        "system": "open-vocab-visual-search",
        "stage": "long-tail-retrieval",
        "theme": "Naming and locating what's in the picture",
        "cluster": "Open-vocabulary vision",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/_results/long-tail-retrieval.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/tests/core.test.js",
        "page": "open-vocab-visual-search.html",
        "status": "complete"
      },
      {
        "id": "open-vocab-visual-search/evidence-inspection",
        "system": "open-vocab-visual-search",
        "stage": "evidence-inspection",
        "theme": "Naming and locating what's in the picture",
        "cluster": "Open-vocabulary vision",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/_results/evidence-inspection.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/open-vocab-visual-search/tests/core.test.js",
        "page": "open-vocab-visual-search.html",
        "status": "complete"
      },
      {
        "id": "vlm-grounded-reasoning/look-then-reason",
        "system": "vlm-grounded-reasoning",
        "stage": "look-then-reason",
        "theme": "Teaching machines to see and talk at once",
        "cluster": "Vision-language reasoning",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/_results/look-then-reason.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/tests/core.test.js",
        "page": "vlm-grounded-reasoning.html",
        "status": "complete"
      },
      {
        "id": "vlm-grounded-reasoning/hallucination-check",
        "system": "vlm-grounded-reasoning",
        "stage": "hallucination-check",
        "theme": "Teaching machines to see and talk at once",
        "cluster": "Vision-language reasoning",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/_results/hallucination-check.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/tests/core.test.js",
        "page": "vlm-grounded-reasoning.html",
        "status": "complete"
      },
      {
        "id": "vlm-grounded-reasoning/tool-verified-answer",
        "system": "vlm-grounded-reasoning",
        "stage": "tool-verified-answer",
        "theme": "Teaching machines to see and talk at once",
        "cluster": "Vision-language reasoning",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/_results/tool-verified-answer.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/vlm-grounded-reasoning/tests/core.test.js",
        "page": "vlm-grounded-reasoning.html",
        "status": "complete"
      },
      {
        "id": "efficient-vision-serving/token-budget",
        "system": "efficient-vision-serving",
        "stage": "token-budget",
        "theme": "Learning more from less, and not breaking",
        "cluster": "Efficient vision",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/_results/token-budget.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/tests/core.test.js",
        "page": "efficient-vision-serving.html",
        "status": "complete"
      },
      {
        "id": "efficient-vision-serving/quantized-serving",
        "system": "efficient-vision-serving",
        "stage": "quantized-serving",
        "theme": "Learning more from less, and not breaking",
        "cluster": "Efficient vision",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/_results/quantized-serving.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/tests/core.test.js",
        "page": "efficient-vision-serving.html",
        "status": "complete"
      },
      {
        "id": "efficient-vision-serving/student-routing",
        "system": "efficient-vision-serving",
        "stage": "student-routing",
        "theme": "Learning more from less, and not breaking",
        "cluster": "Efficient vision",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/_results/student-routing.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/efficient-vision-serving/tests/core.test.js",
        "page": "efficient-vision-serving.html",
        "status": "complete"
      },
      {
        "id": "metric-3d-reconstruction/camera-geometry",
        "system": "metric-3d-reconstruction",
        "stage": "camera-geometry",
        "theme": "Recovering the 3D world from flat pictures",
        "cluster": "3D reconstruction and novel views",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/_results/camera-geometry.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/tests/core.test.js",
        "page": "metric-3d-reconstruction.html",
        "status": "complete"
      },
      {
        "id": "metric-3d-reconstruction/metric-scale",
        "system": "metric-3d-reconstruction",
        "stage": "metric-scale",
        "theme": "Recovering the 3D world from flat pictures",
        "cluster": "3D reconstruction and novel views",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/_results/metric-scale.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/tests/core.test.js",
        "page": "metric-3d-reconstruction.html",
        "status": "complete"
      },
      {
        "id": "metric-3d-reconstruction/surface-consistency",
        "system": "metric-3d-reconstruction",
        "stage": "surface-consistency",
        "theme": "Recovering the 3D world from flat pictures",
        "cluster": "3D reconstruction and novel views",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/_results/surface-consistency.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/metric-3d-reconstruction/tests/core.test.js",
        "page": "metric-3d-reconstruction.html",
        "status": "complete"
      },
      {
        "id": "gaussian-splatting-platform/splat-fit",
        "system": "gaussian-splatting-platform",
        "stage": "splat-fit",
        "theme": "Recovering the 3D world from flat pictures",
        "cluster": "Gaussian Splatting",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/_results/splat-fit.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/tests/core.test.js",
        "page": "gaussian-splatting-platform.html",
        "status": "complete"
      },
      {
        "id": "gaussian-splatting-platform/semantic-splats",
        "system": "gaussian-splatting-platform",
        "stage": "semantic-splats",
        "theme": "Recovering the 3D world from flat pictures",
        "cluster": "Gaussian Splatting",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/_results/semantic-splats.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/tests/core.test.js",
        "page": "gaussian-splatting-platform.html",
        "status": "complete"
      },
      {
        "id": "gaussian-splatting-platform/watermark-provenance",
        "system": "gaussian-splatting-platform",
        "stage": "watermark-provenance",
        "theme": "Recovering the 3D world from flat pictures",
        "cluster": "Gaussian Splatting",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/_results/watermark-provenance.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/gaussian-splatting-platform/tests/core.test.js",
        "page": "gaussian-splatting-platform.html",
        "status": "complete"
      },
      {
        "id": "video-world-model/temporal-memory",
        "system": "video-world-model",
        "stage": "temporal-memory",
        "theme": "Seeing and making things that move",
        "cluster": "Video generation and world models",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/_results/temporal-memory.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/tests/core.test.js",
        "page": "video-world-model.html",
        "status": "complete"
      },
      {
        "id": "video-world-model/physics-consistency",
        "system": "video-world-model",
        "stage": "physics-consistency",
        "theme": "Seeing and making things that move",
        "cluster": "Video generation and world models",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/_results/physics-consistency.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/tests/core.test.js",
        "page": "video-world-model.html",
        "status": "complete"
      },
      {
        "id": "video-world-model/future-rollout",
        "system": "video-world-model",
        "stage": "future-rollout",
        "theme": "Seeing and making things that move",
        "cluster": "Video generation and world models",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/_results/future-rollout.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/video-world-model/tests/core.test.js",
        "page": "video-world-model.html",
        "status": "complete"
      },
      {
        "id": "controllable-generation-studio/layout-control",
        "system": "controllable-generation-studio",
        "stage": "layout-control",
        "theme": "Making pixels from meaning",
        "cluster": "Controllable generation",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/_results/layout-control.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/tests/core.test.js",
        "page": "controllable-generation-studio.html",
        "status": "complete"
      },
      {
        "id": "controllable-generation-studio/identity-preservation",
        "system": "controllable-generation-studio",
        "stage": "identity-preservation",
        "theme": "Making pixels from meaning",
        "cluster": "Controllable generation",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/_results/identity-preservation.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/tests/core.test.js",
        "page": "controllable-generation-studio.html",
        "status": "complete"
      },
      {
        "id": "controllable-generation-studio/preference-reward",
        "system": "controllable-generation-studio",
        "stage": "preference-reward",
        "theme": "Making pixels from meaning",
        "cluster": "Controllable generation",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/_results/preference-reward.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/controllable-generation-studio/tests/core.test.js",
        "page": "controllable-generation-studio.html",
        "status": "complete"
      },
      {
        "id": "restoration-reliability-stack/degradation-diagnosis",
        "system": "restoration-reliability-stack",
        "stage": "degradation-diagnosis",
        "theme": "Making pixels from meaning",
        "cluster": "Image restoration",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/_results/degradation-diagnosis.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/tests/core.test.js",
        "page": "restoration-reliability-stack.html",
        "status": "complete"
      },
      {
        "id": "restoration-reliability-stack/fidelity-gate",
        "system": "restoration-reliability-stack",
        "stage": "fidelity-gate",
        "theme": "Making pixels from meaning",
        "cluster": "Image restoration",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/_results/fidelity-gate.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/tests/core.test.js",
        "page": "restoration-reliability-stack.html",
        "status": "complete"
      },
      {
        "id": "restoration-reliability-stack/downstream-validation",
        "system": "restoration-reliability-stack",
        "stage": "downstream-validation",
        "theme": "Making pixels from meaning",
        "cluster": "Image restoration",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/_results/downstream-validation.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/restoration-reliability-stack/tests/core.test.js",
        "page": "restoration-reliability-stack.html",
        "status": "complete"
      },
      {
        "id": "medical-vision-validation/domain-shift",
        "system": "medical-vision-validation",
        "stage": "domain-shift",
        "theme": "The frontier - new senses and new duties",
        "cluster": "Vision for science and medicine",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/_results/domain-shift.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/tests/core.test.js",
        "page": "medical-vision-validation.html",
        "status": "complete"
      },
      {
        "id": "medical-vision-validation/uncertainty-triage",
        "system": "medical-vision-validation",
        "stage": "uncertainty-triage",
        "theme": "The frontier - new senses and new duties",
        "cluster": "Vision for science and medicine",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/_results/uncertainty-triage.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/tests/core.test.js",
        "page": "medical-vision-validation.html",
        "status": "complete"
      },
      {
        "id": "medical-vision-validation/clinical-evidence",
        "system": "medical-vision-validation",
        "stage": "clinical-evidence",
        "theme": "The frontier - new senses and new duties",
        "cluster": "Vision for science and medicine",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/_results/clinical-evidence.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/medical-vision-validation/tests/core.test.js",
        "page": "medical-vision-validation.html",
        "status": "complete"
      },
      {
        "id": "driving-vla-release-gate/scene-grounding",
        "system": "driving-vla-release-gate",
        "stage": "scene-grounding",
        "theme": "Using vision to act in the world",
        "cluster": "Driving and vision-language-action",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/_results/scene-grounding.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/tests/core.test.js",
        "page": "driving-vla-release-gate.html",
        "status": "complete"
      },
      {
        "id": "driving-vla-release-gate/risk-anticipation",
        "system": "driving-vla-release-gate",
        "stage": "risk-anticipation",
        "theme": "Using vision to act in the world",
        "cluster": "Driving and vision-language-action",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/_results/risk-anticipation.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/tests/core.test.js",
        "page": "driving-vla-release-gate.html",
        "status": "complete"
      },
      {
        "id": "driving-vla-release-gate/action-release",
        "system": "driving-vla-release-gate",
        "stage": "action-release",
        "theme": "Using vision to act in the world",
        "cluster": "Driving and vision-language-action",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/_results/action-release.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/driving-vla-release-gate/tests/core.test.js",
        "page": "driving-vla-release-gate.html",
        "status": "complete"
      },
      {
        "id": "adversarial-provenance-gate/attack-surface",
        "system": "adversarial-provenance-gate",
        "stage": "attack-surface",
        "theme": "The frontier - new senses and new duties",
        "cluster": "Adversarial robustness",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/_results/attack-surface.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/tests/core.test.js",
        "page": "adversarial-provenance-gate.html",
        "status": "complete"
      },
      {
        "id": "adversarial-provenance-gate/provenance-detection",
        "system": "adversarial-provenance-gate",
        "stage": "provenance-detection",
        "theme": "The frontier - new senses and new duties",
        "cluster": "Adversarial robustness",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/_results/provenance-detection.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/tests/core.test.js",
        "page": "adversarial-provenance-gate.html",
        "status": "complete"
      },
      {
        "id": "adversarial-provenance-gate/unlearning-check",
        "system": "adversarial-provenance-gate",
        "stage": "unlearning-check",
        "theme": "The frontier - new senses and new duties",
        "cluster": "Adversarial robustness",
        "result": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/_results/unlearning-check.json",
        "core": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/src/core.js",
        "test": "/home/manishmehta/ui-projects/cvpr-2026-site/source-code/learning/adversarial-provenance-gate/tests/core.test.js",
        "page": "adversarial-provenance-gate.html",
        "status": "complete"
      }
    ]
  },
  "themeMatrix": {
    "summary": {
      "matrix": "cvpr-theme-release-matrix",
      "status": "release",
      "themes": 8,
      "systems": 11,
      "stages": 33,
      "demos": 41,
      "coveredThemes": 8,
      "openThemes": 0,
      "clustersCovered": 11,
      "benchSystems": 11,
      "benchCases": 44,
      "benchBlocks": 0,
      "receiptStatus": "ready",
      "receiptArtifacts": 7,
      "validationGate": "release",
      "packageTests": 148
    },
    "themeRows": [
      {
        "theme": "The frontier - new senses and new duties",
        "systems": 2,
        "systemSlugs": [
          "adversarial-provenance-gate",
          "medical-vision-validation"
        ],
        "stages": 6,
        "stageDemos": 6,
        "flagshipDemos": 0,
        "benches": 2,
        "benchCases": 8,
        "benchBlocks": 0,
        "pages": [
          "adversarial-provenance-gate.html",
          "medical-vision-validation.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Recovering the 3D world from flat pictures",
        "systems": 2,
        "systemSlugs": [
          "gaussian-splatting-platform",
          "metric-3d-reconstruction"
        ],
        "stages": 6,
        "stageDemos": 6,
        "flagshipDemos": 0,
        "benches": 2,
        "benchCases": 8,
        "benchBlocks": 0,
        "pages": [
          "gaussian-splatting-platform.html",
          "metric-3d-reconstruction.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Seeing and making things that move",
        "systems": 1,
        "systemSlugs": [
          "video-world-model"
        ],
        "stages": 3,
        "stageDemos": 3,
        "flagshipDemos": 0,
        "benches": 1,
        "benchCases": 4,
        "benchBlocks": 0,
        "pages": [
          "video-world-model.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Making pixels from meaning",
        "systems": 2,
        "systemSlugs": [
          "controllable-generation-studio",
          "restoration-reliability-stack"
        ],
        "stages": 6,
        "stageDemos": 6,
        "flagshipDemos": 0,
        "benches": 2,
        "benchCases": 8,
        "benchBlocks": 0,
        "pages": [
          "controllable-generation-studio.html",
          "restoration-reliability-stack.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Teaching machines to see and talk at once",
        "systems": 1,
        "systemSlugs": [
          "vlm-grounded-reasoning"
        ],
        "stages": 3,
        "stageDemos": 3,
        "flagshipDemos": 0,
        "benches": 1,
        "benchCases": 4,
        "benchBlocks": 0,
        "pages": [
          "vlm-grounded-reasoning.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Naming and locating what's in the picture",
        "systems": 1,
        "systemSlugs": [
          "open-vocab-visual-search"
        ],
        "stages": 3,
        "stageDemos": 3,
        "flagshipDemos": 0,
        "benches": 1,
        "benchCases": 4,
        "benchBlocks": 0,
        "pages": [
          "open-vocab-visual-search.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Using vision to act in the world",
        "systems": 1,
        "systemSlugs": [
          "driving-vla-release-gate"
        ],
        "stages": 3,
        "stageDemos": 3,
        "flagshipDemos": 0,
        "benches": 1,
        "benchCases": 4,
        "benchBlocks": 0,
        "pages": [
          "driving-vla-release-gate.html"
        ],
        "status": "covered"
      },
      {
        "theme": "Learning more from less, and not breaking",
        "systems": 1,
        "systemSlugs": [
          "efficient-vision-serving"
        ],
        "stages": 3,
        "stageDemos": 3,
        "flagshipDemos": 0,
        "benches": 1,
        "benchCases": 4,
        "benchBlocks": 0,
        "pages": [
          "efficient-vision-serving.html"
        ],
        "status": "covered"
      }
    ],
    "sourceRegistries": {
      "systems": "analysis/cvpr_systems/registry.json",
      "demos": "analysis/cvpr_demos/registry.json",
      "mission": "analysis/cvpr_mission_control/registry.json",
      "receipt": "analysis/cvpr_colab_run_receipt/registry.json",
      "validation": "analysis/cvpr_validation_center/registry.json"
    }
  },
  "cockpit": {
    "summary": {
      "cockpit": "cvpr-demo-evidence-cockpit",
      "status": "ready",
      "systems": 11,
      "stageDemos": 33,
      "flagshipDemos": 8,
      "totalDemos": 41,
      "proPlusJobs": 10,
      "proPlusWaves": 3,
      "expectedLiveResults": 40,
      "cachedResults": 40,
      "benchRelease": 44,
      "benchCases": 44,
      "missingDemoEvidence": 0,
      "gpuBackedStageDemos": 30,
      "systemEvidenceStageDemos": 3,
      "releaseGate": "release",
      "fullStackStatus": "valid"
    },
    "systemRows": [
      {
        "system": "adversarial-provenance-gate",
        "theme": "The frontier - new senses and new duties",
        "bench": "cvpr-adversarial-provenance-bench",
        "benchPage": "cvpr-adversarial-provenance-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "adversarial-provenance",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "inspectPage": "adversarial-provenance-gate.html",
        "status": "ready"
      },
      {
        "system": "controllable-generation-studio",
        "theme": "Making pixels from meaning",
        "bench": "cvpr-constraint-generation-bench",
        "benchPage": "cvpr-constraint-generation-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "constraint-generation",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "inspectPage": "controllable-generation-studio.html",
        "status": "ready"
      },
      {
        "system": "driving-vla-release-gate",
        "theme": "Using vision to act in the world",
        "bench": "cvpr-driving-safety-bench",
        "benchPage": "cvpr-driving-safety-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "driving-safety",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "inspectPage": "driving-vla-release-gate.html",
        "status": "ready"
      },
      {
        "system": "efficient-vision-serving",
        "theme": "Learning more from less, and not breaking",
        "bench": "cvpr-compute-serving-bench",
        "benchPage": "cvpr-compute-serving-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "compute-serving",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "inspectPage": "efficient-vision-serving.html",
        "status": "ready"
      },
      {
        "system": "gaussian-splatting-platform",
        "theme": "Recovering the 3D world from flat pictures",
        "bench": "cvpr-gaussian-splatting-bench",
        "benchPage": "cvpr-gaussian-splatting-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "gaussian-splatting",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "inspectPage": "gaussian-splatting-platform.html",
        "status": "ready"
      },
      {
        "system": "medical-vision-validation",
        "theme": "The frontier - new senses and new duties",
        "bench": "cvpr-clinical-shift-bench",
        "benchPage": "cvpr-clinical-shift-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "clinical-shift",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "inspectPage": "medical-vision-validation.html",
        "status": "ready"
      },
      {
        "system": "metric-3d-reconstruction",
        "theme": "Recovering the 3D world from flat pictures",
        "bench": "cvpr-metric-geometry-bench",
        "benchPage": "cvpr-metric-geometry-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "metric-geometry",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "inspectPage": "metric-3d-reconstruction.html",
        "status": "ready"
      },
      {
        "system": "open-vocab-visual-search",
        "theme": "Naming and locating what's in the picture",
        "bench": "cvpr-long-tail-grounding-bench",
        "benchPage": "cvpr-long-tail-grounding-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "open-vocab-grounding",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "inspectPage": "open-vocab-visual-search.html",
        "status": "ready"
      },
      {
        "system": "restoration-reliability-stack",
        "theme": "Making pixels from meaning",
        "bench": "cvpr-restoration-fidelity-bench",
        "benchPage": "cvpr-restoration-fidelity-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "restoration-fidelity",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "inspectPage": "restoration-reliability-stack.html",
        "status": "ready"
      },
      {
        "system": "video-world-model",
        "theme": "Seeing and making things that move",
        "bench": "cvpr-temporal-rollout-bench",
        "benchPage": "cvpr-temporal-rollout-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "temporal-rollout",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "inspectPage": "video-world-model.html",
        "status": "ready"
      },
      {
        "system": "vlm-grounded-reasoning",
        "theme": "Teaching machines to see and talk at once",
        "bench": "cvpr-vlm-answer-verification-bench",
        "benchPage": "cvpr-vlm-answer-verification-bench.html",
        "stageDemos": 3,
        "benchRelease": 4,
        "benchCases": 4,
        "runtimeEvidence": "cached-system-evidence",
        "colabJobId": "",
        "wave": "cached-system-evidence",
        "expectedLiveResults": 0,
        "inspectPage": "vlm-grounded-reasoning.html",
        "status": "ready"
      }
    ],
    "demoRows": [
      {
        "demoId": "stage-open-vocab-visual-search-text-query-grounding",
        "title": "Ground text queries in visible regions",
        "system": "open-vocab-visual-search",
        "theme": "Naming and locating what's in the picture",
        "sourceStage": "text-query-grounding",
        "visualMode": "localization",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "open-vocab-visual-search.html",
        "bench": "cvpr-long-tail-grounding-bench",
        "benchPage": "cvpr-long-tail-grounding-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "open-vocab-grounding",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-open-vocab-visual-search-long-tail-retrieval",
        "title": "Retrieve long-tail objects",
        "system": "open-vocab-visual-search",
        "theme": "Naming and locating what's in the picture",
        "sourceStage": "long-tail-retrieval",
        "visualMode": "localization",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "open-vocab-visual-search.html",
        "bench": "cvpr-long-tail-grounding-bench",
        "benchPage": "cvpr-long-tail-grounding-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "open-vocab-grounding",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-open-vocab-visual-search-evidence-inspection",
        "title": "Expose search evidence",
        "system": "open-vocab-visual-search",
        "theme": "Naming and locating what's in the picture",
        "sourceStage": "evidence-inspection",
        "visualMode": "localization",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "open-vocab-visual-search.html",
        "bench": "cvpr-long-tail-grounding-bench",
        "benchPage": "cvpr-long-tail-grounding-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "open-vocab-grounding",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-vlm-grounded-reasoning-look-then-reason",
        "title": "Look before reasoning",
        "system": "vlm-grounded-reasoning",
        "theme": "Teaching machines to see and talk at once",
        "sourceStage": "look-then-reason",
        "visualMode": "grounding",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "vlm-grounded-reasoning.html",
        "bench": "cvpr-vlm-answer-verification-bench",
        "benchPage": "cvpr-vlm-answer-verification-bench.html",
        "runtimeEvidence": "cached-system-evidence",
        "colabJobId": "",
        "wave": "cached-system-evidence",
        "expectedLiveResults": 0,
        "status": "ready"
      },
      {
        "demoId": "stage-vlm-grounded-reasoning-hallucination-check",
        "title": "Check hallucinated claims",
        "system": "vlm-grounded-reasoning",
        "theme": "Teaching machines to see and talk at once",
        "sourceStage": "hallucination-check",
        "visualMode": "grounding",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "vlm-grounded-reasoning.html",
        "bench": "cvpr-vlm-answer-verification-bench",
        "benchPage": "cvpr-vlm-answer-verification-bench.html",
        "runtimeEvidence": "cached-system-evidence",
        "colabJobId": "",
        "wave": "cached-system-evidence",
        "expectedLiveResults": 0,
        "status": "ready"
      },
      {
        "demoId": "stage-vlm-grounded-reasoning-tool-verified-answer",
        "title": "Verify with visual tools",
        "system": "vlm-grounded-reasoning",
        "theme": "Teaching machines to see and talk at once",
        "sourceStage": "tool-verified-answer",
        "visualMode": "grounding",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "vlm-grounded-reasoning.html",
        "bench": "cvpr-vlm-answer-verification-bench",
        "benchPage": "cvpr-vlm-answer-verification-bench.html",
        "runtimeEvidence": "cached-system-evidence",
        "colabJobId": "",
        "wave": "cached-system-evidence",
        "expectedLiveResults": 0,
        "status": "ready"
      },
      {
        "demoId": "stage-efficient-vision-serving-token-budget",
        "title": "Control token budget",
        "system": "efficient-vision-serving",
        "theme": "Learning more from less, and not breaking",
        "sourceStage": "token-budget",
        "visualMode": "efficiency",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "efficient-vision-serving.html",
        "bench": "cvpr-compute-serving-bench",
        "benchPage": "cvpr-compute-serving-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "compute-serving",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-efficient-vision-serving-quantized-serving",
        "title": "Serve quantized models",
        "system": "efficient-vision-serving",
        "theme": "Learning more from less, and not breaking",
        "sourceStage": "quantized-serving",
        "visualMode": "efficiency",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "efficient-vision-serving.html",
        "bench": "cvpr-compute-serving-bench",
        "benchPage": "cvpr-compute-serving-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "compute-serving",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-efficient-vision-serving-student-routing",
        "title": "Route to small students",
        "system": "efficient-vision-serving",
        "theme": "Learning more from less, and not breaking",
        "sourceStage": "student-routing",
        "visualMode": "efficiency",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "efficient-vision-serving.html",
        "bench": "cvpr-compute-serving-bench",
        "benchPage": "cvpr-compute-serving-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "compute-serving",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-metric-3d-reconstruction-camera-geometry",
        "title": "Recover camera geometry",
        "system": "metric-3d-reconstruction",
        "theme": "Recovering the 3D world from flat pictures",
        "sourceStage": "camera-geometry",
        "visualMode": "geometry",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "metric-3d-reconstruction.html",
        "bench": "cvpr-metric-geometry-bench",
        "benchPage": "cvpr-metric-geometry-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "metric-geometry",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-metric-3d-reconstruction-metric-scale",
        "title": "Recover metric scale",
        "system": "metric-3d-reconstruction",
        "theme": "Recovering the 3D world from flat pictures",
        "sourceStage": "metric-scale",
        "visualMode": "geometry",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "metric-3d-reconstruction.html",
        "bench": "cvpr-metric-geometry-bench",
        "benchPage": "cvpr-metric-geometry-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "metric-geometry",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-metric-3d-reconstruction-surface-consistency",
        "title": "Check surface consistency",
        "system": "metric-3d-reconstruction",
        "theme": "Recovering the 3D world from flat pictures",
        "sourceStage": "surface-consistency",
        "visualMode": "geometry",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "metric-3d-reconstruction.html",
        "bench": "cvpr-metric-geometry-bench",
        "benchPage": "cvpr-metric-geometry-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "metric-geometry",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-gaussian-splatting-platform-splat-fit",
        "title": "Fit renderable splats",
        "system": "gaussian-splatting-platform",
        "theme": "Recovering the 3D world from flat pictures",
        "sourceStage": "splat-fit",
        "visualMode": "splats",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "gaussian-splatting-platform.html",
        "bench": "cvpr-gaussian-splatting-bench",
        "benchPage": "cvpr-gaussian-splatting-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "gaussian-splatting",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-gaussian-splatting-platform-semantic-splats",
        "title": "Attach semantic labels",
        "system": "gaussian-splatting-platform",
        "theme": "Recovering the 3D world from flat pictures",
        "sourceStage": "semantic-splats",
        "visualMode": "splats",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "gaussian-splatting-platform.html",
        "bench": "cvpr-gaussian-splatting-bench",
        "benchPage": "cvpr-gaussian-splatting-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "gaussian-splatting",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-gaussian-splatting-platform-watermark-provenance",
        "title": "Track provenance",
        "system": "gaussian-splatting-platform",
        "theme": "Recovering the 3D world from flat pictures",
        "sourceStage": "watermark-provenance",
        "visualMode": "splats",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "gaussian-splatting-platform.html",
        "bench": "cvpr-gaussian-splatting-bench",
        "benchPage": "cvpr-gaussian-splatting-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "gaussian-splatting",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-video-world-model-temporal-memory",
        "title": "Keep temporal memory",
        "system": "video-world-model",
        "theme": "Seeing and making things that move",
        "sourceStage": "temporal-memory",
        "visualMode": "temporal",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "video-world-model.html",
        "bench": "cvpr-temporal-rollout-bench",
        "benchPage": "cvpr-temporal-rollout-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "temporal-rollout",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-video-world-model-physics-consistency",
        "title": "Check physics consistency",
        "system": "video-world-model",
        "theme": "Seeing and making things that move",
        "sourceStage": "physics-consistency",
        "visualMode": "temporal",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "video-world-model.html",
        "bench": "cvpr-temporal-rollout-bench",
        "benchPage": "cvpr-temporal-rollout-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "temporal-rollout",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-video-world-model-future-rollout",
        "title": "Score future rollouts",
        "system": "video-world-model",
        "theme": "Seeing and making things that move",
        "sourceStage": "future-rollout",
        "visualMode": "temporal",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "video-world-model.html",
        "bench": "cvpr-temporal-rollout-bench",
        "benchPage": "cvpr-temporal-rollout-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "temporal-rollout",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-controllable-generation-studio-layout-control",
        "title": "Control layout",
        "system": "controllable-generation-studio",
        "theme": "Making pixels from meaning",
        "sourceStage": "layout-control",
        "visualMode": "editing",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "controllable-generation-studio.html",
        "bench": "cvpr-constraint-generation-bench",
        "benchPage": "cvpr-constraint-generation-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "constraint-generation",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-controllable-generation-studio-identity-preservation",
        "title": "Preserve identity",
        "system": "controllable-generation-studio",
        "theme": "Making pixels from meaning",
        "sourceStage": "identity-preservation",
        "visualMode": "editing",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "controllable-generation-studio.html",
        "bench": "cvpr-constraint-generation-bench",
        "benchPage": "cvpr-constraint-generation-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "constraint-generation",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-controllable-generation-studio-preference-reward",
        "title": "Optimize preference reward",
        "system": "controllable-generation-studio",
        "theme": "Making pixels from meaning",
        "sourceStage": "preference-reward",
        "visualMode": "editing",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "controllable-generation-studio.html",
        "bench": "cvpr-constraint-generation-bench",
        "benchPage": "cvpr-constraint-generation-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "constraint-generation",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-restoration-reliability-stack-degradation-diagnosis",
        "title": "Diagnose degradation",
        "system": "restoration-reliability-stack",
        "theme": "Making pixels from meaning",
        "sourceStage": "degradation-diagnosis",
        "visualMode": "restoration",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "restoration-reliability-stack.html",
        "bench": "cvpr-restoration-fidelity-bench",
        "benchPage": "cvpr-restoration-fidelity-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "restoration-fidelity",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-restoration-reliability-stack-fidelity-gate",
        "title": "Gate restoration fidelity",
        "system": "restoration-reliability-stack",
        "theme": "Making pixels from meaning",
        "sourceStage": "fidelity-gate",
        "visualMode": "restoration",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "restoration-reliability-stack.html",
        "bench": "cvpr-restoration-fidelity-bench",
        "benchPage": "cvpr-restoration-fidelity-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "restoration-fidelity",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-restoration-reliability-stack-downstream-validation",
        "title": "Validate downstream utility",
        "system": "restoration-reliability-stack",
        "theme": "Making pixels from meaning",
        "sourceStage": "downstream-validation",
        "visualMode": "restoration",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "restoration-reliability-stack.html",
        "bench": "cvpr-restoration-fidelity-bench",
        "benchPage": "cvpr-restoration-fidelity-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "restoration-fidelity",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-medical-vision-validation-domain-shift",
        "title": "Measure domain shift",
        "system": "medical-vision-validation",
        "theme": "The frontier - new senses and new duties",
        "sourceStage": "domain-shift",
        "visualMode": "medical",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "medical-vision-validation.html",
        "bench": "cvpr-clinical-shift-bench",
        "benchPage": "cvpr-clinical-shift-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "clinical-shift",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-medical-vision-validation-uncertainty-triage",
        "title": "Triage uncertainty",
        "system": "medical-vision-validation",
        "theme": "The frontier - new senses and new duties",
        "sourceStage": "uncertainty-triage",
        "visualMode": "medical",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "medical-vision-validation.html",
        "bench": "cvpr-clinical-shift-bench",
        "benchPage": "cvpr-clinical-shift-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "clinical-shift",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-medical-vision-validation-clinical-evidence",
        "title": "Build clinical evidence",
        "system": "medical-vision-validation",
        "theme": "The frontier - new senses and new duties",
        "sourceStage": "clinical-evidence",
        "visualMode": "medical",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "medical-vision-validation.html",
        "bench": "cvpr-clinical-shift-bench",
        "benchPage": "cvpr-clinical-shift-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "clinical-shift",
        "wave": "wave-2-temporal-clinical-serving",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-driving-vla-release-gate-scene-grounding",
        "title": "Ground the driving scene",
        "system": "driving-vla-release-gate",
        "theme": "Using vision to act in the world",
        "sourceStage": "scene-grounding",
        "visualMode": "safety",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "driving-vla-release-gate.html",
        "bench": "cvpr-driving-safety-bench",
        "benchPage": "cvpr-driving-safety-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "driving-safety",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-driving-vla-release-gate-risk-anticipation",
        "title": "Anticipate risk",
        "system": "driving-vla-release-gate",
        "theme": "Using vision to act in the world",
        "sourceStage": "risk-anticipation",
        "visualMode": "safety",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "driving-vla-release-gate.html",
        "bench": "cvpr-driving-safety-bench",
        "benchPage": "cvpr-driving-safety-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "driving-safety",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-driving-vla-release-gate-action-release",
        "title": "Gate action release",
        "system": "driving-vla-release-gate",
        "theme": "Using vision to act in the world",
        "sourceStage": "action-release",
        "visualMode": "safety",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "driving-vla-release-gate.html",
        "bench": "cvpr-driving-safety-bench",
        "benchPage": "cvpr-driving-safety-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "driving-safety",
        "wave": "wave-3-generation-driving-3d",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-adversarial-provenance-gate-attack-surface",
        "title": "Map attack surface",
        "system": "adversarial-provenance-gate",
        "theme": "The frontier - new senses and new duties",
        "sourceStage": "attack-surface",
        "visualMode": "trust",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "adversarial-provenance-gate.html",
        "bench": "cvpr-adversarial-provenance-bench",
        "benchPage": "cvpr-adversarial-provenance-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "adversarial-provenance",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-adversarial-provenance-gate-provenance-detection",
        "title": "Detect provenance",
        "system": "adversarial-provenance-gate",
        "theme": "The frontier - new senses and new duties",
        "sourceStage": "provenance-detection",
        "visualMode": "trust",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "adversarial-provenance-gate.html",
        "bench": "cvpr-adversarial-provenance-bench",
        "benchPage": "cvpr-adversarial-provenance-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "adversarial-provenance",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      },
      {
        "demoId": "stage-adversarial-provenance-gate-unlearning-check",
        "title": "Check unlearning",
        "system": "adversarial-provenance-gate",
        "theme": "The frontier - new senses and new duties",
        "sourceStage": "unlearning-check",
        "visualMode": "trust",
        "demoPage": "cvpr-demo-lab.html",
        "systemPage": "adversarial-provenance-gate.html",
        "bench": "cvpr-adversarial-provenance-bench",
        "benchPage": "cvpr-adversarial-provenance-bench.html",
        "runtimeEvidence": "colab-pro-plus",
        "colabJobId": "adversarial-provenance",
        "wave": "wave-1-grounding-fidelity-provenance",
        "expectedLiveResults": 4,
        "status": "ready"
      }
    ],
    "flagshipRows": [
      {
        "demoId": "open-vocab-grounding",
        "title": "Open-vocabulary region grounding",
        "theme": "Perception",
        "cluster": "Open-vocabulary vision",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "localization",
        "status": "interactive"
      },
      {
        "demoId": "metric-depth-uncertainty",
        "title": "Metric depth uncertainty",
        "theme": "3D",
        "cluster": "3D reconstruction and novel views",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "geometry",
        "status": "interactive"
      },
      {
        "demoId": "temporal-world-rollout",
        "title": "Temporal consistency rollout",
        "theme": "Video",
        "cluster": "Video generation and world models",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "temporal",
        "status": "interactive"
      },
      {
        "demoId": "controlled-editing",
        "title": "Controllable editing preservation",
        "theme": "Generation",
        "cluster": "Controllable generation",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "editing",
        "status": "interactive"
      },
      {
        "demoId": "vlm-grounding-check",
        "title": "Grounded reasoning vs hallucination",
        "theme": "VLM",
        "cluster": "Vision-language reasoning",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "grounding",
        "status": "interactive"
      },
      {
        "demoId": "driving-action-gate",
        "title": "Driving VLA action gate",
        "theme": "Embodied",
        "cluster": "Driving and vision-language-action",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "safety",
        "status": "interactive"
      },
      {
        "demoId": "efficient-token-serving",
        "title": "Token pruning and serving tradeoff",
        "theme": "Learning",
        "cluster": "Efficient vision",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "efficiency",
        "status": "interactive"
      },
      {
        "demoId": "provenance-attack-gate",
        "title": "Provenance and adversarial gate",
        "theme": "Frontier and trust",
        "cluster": "Adversarial robustness",
        "demoPage": "cvpr-demo-lab.html",
        "visualMode": "trust",
        "status": "interactive"
      }
    ],
    "sources": {
      "demos": "analysis/cvpr_demos/registry.json",
      "coverage": "analysis/cvpr_production_coverage_audit/registry.json",
      "planner": "analysis/cvpr_colab_execution_planner/registry.json",
      "mission": "analysis/cvpr_mission_control/registry.json",
      "releaseBrief": "analysis/cvpr_production_release_brief/registry.json"
    }
  },
  "commandCenter": {
    "summary": {
      "center": "cvpr-release-command-center",
      "status": "operator-ready",
      "surfaces": 8,
      "readySurfaces": 8,
      "alerts": 0,
      "importIssues": 0,
      "fullStackStatus": "valid",
      "packageTests": 148,
      "systems": 11,
      "stages": 33,
      "demos": 41,
      "workerJobs": 10,
      "cachedResults": 40
    },
    "surfaceRows": [
      {
        "surface": "cvpr-production-release-brief.html",
        "label": "Production release brief",
        "actual": "release",
        "expected": "release",
        "metric": "8 themes \u00b7 11 systems \u00b7 33 stages \u00b7 41 demos \u00b7 328 arena releases \u00b7 44 bench releases",
        "evidence": "analysis/cvpr_production_release_brief/registry.json",
        "command": "python3 scripts/build_cvpr_production_release_brief.py && python3 scripts/verify_cvpr_production_release_brief.py"
      },
      {
        "surface": "cvpr-launch-readiness-pack.html",
        "label": "Launch readiness pack",
        "actual": "launch-ready",
        "expected": "launch-ready",
        "metric": "148 package tests",
        "evidence": "analysis/cvpr_launch_readiness_pack/registry.json",
        "command": "python3 scripts/build_cvpr_launch_readiness_pack.py && python3 scripts/verify_cvpr_launch_readiness_pack.py"
      },
      {
        "surface": "cvpr-release-manifest.html",
        "label": "Release manifest",
        "actual": "sealed",
        "expected": "sealed",
        "metric": "13 artifacts",
        "evidence": "analysis/cvpr_release_manifest/registry.json",
        "command": "python3 scripts/build_cvpr_release_manifest.py && python3 scripts/verify_cvpr_release_manifest.py"
      },
      {
        "surface": "cvpr-release-change-control.html",
        "label": "Release change control",
        "actual": "controlled",
        "expected": "controlled",
        "metric": "13/13 rows",
        "evidence": "analysis/cvpr_release_change_control/registry.json",
        "command": "python3 scripts/build_cvpr_release_change_control.py && python3 scripts/verify_cvpr_release_change_control.py"
      },
      {
        "surface": "cvpr-release-dependency-graph.html",
        "label": "Release dependency graph",
        "actual": "ready",
        "expected": "ready",
        "metric": "15 nodes / 19 edges",
        "evidence": "analysis/cvpr_release_dependency_graph/registry.json",
        "command": "python3 scripts/build_cvpr_release_dependency_graph.py && python3 scripts/verify_cvpr_release_dependency_graph.py"
      },
      {
        "surface": "cvpr-post-launch-monitoring.html",
        "label": "Post-launch monitoring",
        "actual": "watching",
        "expected": "watching",
        "metric": "9/9 monitors",
        "evidence": "analysis/cvpr_post_launch_monitoring/registry.json",
        "command": "python3 scripts/build_cvpr_post_launch_monitoring.py && python3 scripts/verify_cvpr_post_launch_monitoring.py"
      },
      {
        "surface": "cvpr-release-audit-trail.html",
        "label": "Release audit trail",
        "actual": "complete",
        "expected": "complete",
        "metric": "58/58 events",
        "evidence": "analysis/cvpr_release_audit_trail/registry.json",
        "command": "python3 scripts/build_cvpr_release_audit_trail.py && python3 scripts/verify_cvpr_release_audit_trail.py"
      },
      {
        "surface": "cvpr-validation-center.html",
        "label": "Full-stack validation",
        "actual": "valid",
        "expected": "valid",
        "metric": "99 steps / 148 package tests",
        "evidence": "analysis/cvpr_full_stack_validation/registry.json",
        "command": "python3 scripts/validate_cvpr_full_stack.py"
      }
    ],
    "sources": {
      "brief": "analysis/cvpr_production_release_brief/registry.json",
      "launch": "analysis/cvpr_launch_readiness_pack/registry.json",
      "manifest": "analysis/cvpr_release_manifest/registry.json",
      "changeControl": "analysis/cvpr_release_change_control/registry.json",
      "dependencyGraph": "analysis/cvpr_release_dependency_graph/registry.json",
      "monitoring": "analysis/cvpr_post_launch_monitoring/registry.json",
      "auditTrail": "analysis/cvpr_release_audit_trail/registry.json",
      "validation": "analysis/cvpr_full_stack_validation/registry.json"
    }
  }
};
export const themeRows = [
  {
    "theme": "Learning more from less, and not breaking",
    "systems": 1,
    "stages": 3,
    "stageDemos": 3,
    "benchCases": 4,
    "benchRelease": 4,
    "proPlusSystems": 1,
    "cachedEvidenceSystems": 0,
    "status": "release"
  },
  {
    "theme": "Making pixels from meaning",
    "systems": 2,
    "stages": 6,
    "stageDemos": 6,
    "benchCases": 8,
    "benchRelease": 8,
    "proPlusSystems": 2,
    "cachedEvidenceSystems": 0,
    "status": "release"
  },
  {
    "theme": "Naming and locating what's in the picture",
    "systems": 1,
    "stages": 3,
    "stageDemos": 3,
    "benchCases": 4,
    "benchRelease": 4,
    "proPlusSystems": 1,
    "cachedEvidenceSystems": 0,
    "status": "release"
  },
  {
    "theme": "Recovering the 3D world from flat pictures",
    "systems": 2,
    "stages": 6,
    "stageDemos": 6,
    "benchCases": 8,
    "benchRelease": 8,
    "proPlusSystems": 2,
    "cachedEvidenceSystems": 0,
    "status": "release"
  },
  {
    "theme": "Seeing and making things that move",
    "systems": 1,
    "stages": 3,
    "stageDemos": 3,
    "benchCases": 4,
    "benchRelease": 4,
    "proPlusSystems": 1,
    "cachedEvidenceSystems": 0,
    "status": "release"
  },
  {
    "theme": "Teaching machines to see and talk at once",
    "systems": 1,
    "stages": 3,
    "stageDemos": 3,
    "benchCases": 4,
    "benchRelease": 4,
    "proPlusSystems": 0,
    "cachedEvidenceSystems": 1,
    "status": "release"
  },
  {
    "theme": "The frontier - new senses and new duties",
    "systems": 2,
    "stages": 6,
    "stageDemos": 6,
    "benchCases": 8,
    "benchRelease": 8,
    "proPlusSystems": 2,
    "cachedEvidenceSystems": 0,
    "status": "release"
  },
  {
    "theme": "Using vision to act in the world",
    "systems": 1,
    "stages": 3,
    "stageDemos": 3,
    "benchCases": 4,
    "benchRelease": 4,
    "proPlusSystems": 1,
    "cachedEvidenceSystems": 0,
    "status": "release"
  }
];
export const summary = {
  "portfolio": "cvpr-theme-portfolio-map",
  "status": "release",
  "themes": 8,
  "systems": 11,
  "stages": 33,
  "demos": 41,
  "benchRelease": 44,
  "missingDemoEvidence": 0,
  "proPlusSystems": 10,
  "cachedEvidenceSystems": 1,
  "operatorStatus": "operator-ready"
};
