export const matrixRows = [
  {
    "rank": 1,
    "theme": "frontier",
    "themeName": "The frontier - new senses and new duties",
    "blueprint": "Frontier Sensor Fusion Bench",
    "paperTitle": "MOS: Mitigating Optical-SAR Modality Gap for Cross-Modal Ship Re-Identification",
    "repo": "MOS",
    "repoUrl": "https://github.com/yjzhao1019/MOS",
    "subthemes": [
      "cross-modal retrieval",
      "re-identification",
      "domain adaptation",
      "remote sensing",
      "multimodal learning"
    ],
    "problem": "MOS is about matching ships across optical and SAR imagery. The everyday problem is that optical cameras and radar see the same ship through very different measurement physics.",
    "jobId": "frontier-01-github-com-yjzhao1019-mos",
    "promotedEvidence": true,
    "readiness": 46,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-frontier-mos-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-frontier-mos-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job frontier-01-github-com-yjzhao1019-mos",
    "status": "demo-linked"
  },
  {
    "rank": 2,
    "theme": "frontier",
    "themeName": "The frontier - new senses and new duties",
    "blueprint": "Frontier Sensor Fusion Bench",
    "paperTitle": "SegEarth-R2: Towards Comprehensive Language-guided Segmentation for Remote Sensing Images",
    "repo": "SegEarth-R2",
    "repoUrl": "https://github.com/earth-insights/SegEarth-R2",
    "subthemes": [
      "language-guided-segmentation",
      "remote-sensing",
      "multimodal-learning",
      "geospatial-reasoning",
      "spatial-grounding",
      "hierarchical-granularity"
    ],
    "problem": "SegEarth-R2 is about turning complex language instructions into pixel regions in satellite and aerial images. The everyday problem is that a request may mention several targets, parts of objects, nested categories, or implicit geography, not just a single simp",
    "jobId": "frontier-02-github-com-earth-insights-segear",
    "promotedEvidence": true,
    "readiness": 47,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-frontier-sensor-fusion-bench.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job frontier-02-github-com-earth-insights-segear",
    "status": "demo-linked"
  },
  {
    "rank": 3,
    "theme": "frontier",
    "themeName": "The frontier - new senses and new duties",
    "blueprint": "Frontier Sensor Fusion Bench",
    "paperTitle": "RAVEN: Erasing Invisible Watermarks via Novel View Synthesis",
    "repo": "raven-",
    "repoUrl": "https://github.com/fahadshamshad/raven-",
    "subthemes": [
      "watermark-removal",
      "view-synthesis",
      "security",
      "diffusion-models",
      "adversarial-attack",
      "image-authentication"
    ],
    "problem": "This RAVEN paper is about erasing invisible watermarks. The everyday problem is that watermark signals can survive in images even when they are not visible to people.",
    "jobId": "frontier-03-github-com-fahadshamshad-raven",
    "promotedEvidence": true,
    "readiness": 44,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-frontier-sensor-fusion-bench.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job frontier-03-github-com-fahadshamshad-raven",
    "status": "demo-linked"
  },
  {
    "rank": 4,
    "theme": "frontier",
    "themeName": "The frontier - new senses and new duties",
    "blueprint": "Frontier Sensor Fusion Bench",
    "paperTitle": "MM-OVSeg: Multimodal Optical\u2013SAR Fusion for Open-Vocabulary Segmentation in Remote Sensing",
    "repo": "MM-OVSeg",
    "repoUrl": "https://github.com/Jimmyxichen/MM-OVSeg",
    "subthemes": [
      "open-vocabulary-segmentation",
      "remote-sensing",
      "optical-sar-fusion",
      "multimodal",
      "adverse-weather",
      "earth-observation"
    ],
    "problem": "MM-OVSeg is about open-vocabulary segmentation in remote sensing using optical and SAR data. The everyday problem is that clouds or haze can hide optical imagery, while SAR sees different physical structure.",
    "jobId": "frontier-04-github-com-jimmyxichen-mm-ovseg",
    "promotedEvidence": true,
    "readiness": 31,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-frontier-sensor-fusion-bench.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job frontier-04-github-com-jimmyxichen-mm-ovseg",
    "status": "demo-linked"
  },
  {
    "rank": 5,
    "theme": "frontier",
    "themeName": "The frontier - new senses and new duties",
    "blueprint": "Frontier Sensor Fusion Bench",
    "paperTitle": "GeoViS: Geospatially Rewarded Visual Search for Remote Sensing",
    "repo": "GeoVis",
    "repoUrl": "https://github.com/Zhang-Peirong/GeoVis",
    "subthemes": [
      "depth",
      "generation",
      "geo-localization",
      "multimodal",
      "remote-sensing",
      "transformer"
    ],
    "problem": "GeoViS is about grounding language queries in huge remote-sensing images. The everyday problem is that a target may be tiny inside a kilometer-scale scene, and the query may depend on roads, rivers, relative positions, or distant context.",
    "jobId": "frontier-05-github-com-zhang-peirong-geovis",
    "promotedEvidence": true,
    "readiness": 45,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-frontier-sensor-fusion-bench.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job frontier-05-github-com-zhang-peirong-geovis",
    "status": "demo-linked"
  },
  {
    "rank": 6,
    "theme": "threed",
    "themeName": "Recovering the 3D world from flat pictures",
    "blueprint": "3D World Repo Arena",
    "paperTitle": "Feed-Forward One-Shot Animatable Textured Mesh Avatar Reconstruction",
    "repo": "insightface",
    "repoUrl": "https://github.com/deepinsight/insightface",
    "subthemes": [
      "avatar",
      "3d-reconstruction",
      "mesh",
      "texture-synthesis",
      "feed-forward",
      "human-face"
    ],
    "problem": "This paper is about creating an animatable textured head avatar from one image in a single forward pass. The everyday problem is recovering face shape, hair/head regions, and texture without minutes of per-person optimization.",
    "jobId": "threed-01-github-com-deepinsight-insightfa",
    "promotedEvidence": true,
    "readiness": 51,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-threed-insightface-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-threed-insightface-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job threed-01-github-com-deepinsight-insightfa",
    "status": "demo-linked"
  },
  {
    "rank": 7,
    "theme": "threed",
    "themeName": "Recovering the 3D world from flat pictures",
    "blueprint": "3D World Repo Arena",
    "paperTitle": "Motion-Aware Animatable Gaussian Avatars Deblurring",
    "repo": "MAD-Avatar",
    "repoUrl": "https://github.com/MyNiuuu/MAD-Avatar",
    "subthemes": [
      "avatar reconstruction",
      "video deblurring",
      "3D gaussian splatting",
      "human motion",
      "multi-view geometry",
      "blur formation"
    ],
    "problem": "Motion-Aware Gaussian Avatars Deblurring is about building sharp animatable avatars from blurry videos. The everyday problem is that fast human movement smears frames, and 2D deblurring can disagree across camera views.",
    "jobId": "threed-02-github-com-myniuuu-mad-avatar",
    "promotedEvidence": true,
    "readiness": 41,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-3d-world-repo-arena.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job threed-02-github-com-myniuuu-mad-avatar",
    "status": "demo-linked"
  },
  {
    "rank": 8,
    "theme": "threed",
    "themeName": "Recovering the 3D world from flat pictures",
    "blueprint": "3D World Repo Arena",
    "paperTitle": "L2DGS: Low-Light Dynamic Gaussian Splatting",
    "repo": "L2DGS",
    "repoUrl": "https://github.com/akumar005/L2DGS",
    "subthemes": [
      "low-light-imaging",
      "dynamic-scene-reconstruction",
      "gaussian-splatting",
      "illumination-handling",
      "4d-reconstruction",
      "scene-decomposition"
    ],
    "problem": "L2DGS is about reconstructing a well-lit dynamic scene from low-light video. The everyday problem is that darkness, motion, shadows, occlusion, and exposure changes all hide the same underlying moving geometry.",
    "jobId": "threed-03-github-com-akumar005-l2dgs",
    "promotedEvidence": true,
    "readiness": 34,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-3d-world-repo-arena.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job threed-03-github-com-akumar005-l2dgs",
    "status": "demo-linked"
  },
  {
    "rank": 9,
    "theme": "threed",
    "themeName": "Recovering the 3D world from flat pictures",
    "blueprint": "3D World Repo Arena",
    "paperTitle": "Flow4DGS-SLAM: Optical Flow-Guided 4D Gaussian Splatting SLAM",
    "repo": "Flow4DGS-SLAM",
    "repoUrl": "https://github.com/wangys16/Flow4DGS-SLAM",
    "subthemes": [
      "SLAM",
      "3d-gaussian-splatting",
      "4d-reconstruction",
      "optical-flow",
      "dynamic-scenes",
      "motion-estimation"
    ],
    "problem": "Flow4DGS-SLAM is about mapping dynamic scenes while tracking camera motion. The everyday problem is that moving objects confuse a map unless the system separates camera movement from scene movement.",
    "jobId": "threed-04-github-com-wangys16-flow4dgs-sla",
    "promotedEvidence": true,
    "readiness": 35,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-3d-world-repo-arena.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job threed-04-github-com-wangys16-flow4dgs-sla",
    "status": "demo-linked"
  },
  {
    "rank": 10,
    "theme": "threed",
    "themeName": "Recovering the 3D world from flat pictures",
    "blueprint": "3D World Repo Arena",
    "paperTitle": "Prune Wisely, Reconstruct Sharply: Compact 3D Gaussian Splatting via Adaptive Pruning and Difference-of-Gaussian Primitives",
    "repo": "Prune-Wisely-",
    "repoUrl": "https://github.com/WangHaoran16/Prune-Wisely-",
    "subthemes": [
      "3d-reconstruction",
      "gaussian-splatting",
      "novel-view-synthesis",
      "model-compression",
      "pruning",
      "rendering"
    ],
    "problem": "This paper is about making 3D Gaussian Splatting smaller without losing sharp rendering. The everyday problem is that many Gaussians are redundant, but pruning the wrong ones removes real detail.",
    "jobId": "threed-05-github-com-wanghaoran16-prune-wi",
    "promotedEvidence": true,
    "readiness": 48,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-3d-world-repo-arena.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job threed-05-github-com-wanghaoran16-prune-wi",
    "status": "demo-linked"
  },
  {
    "rank": 11,
    "theme": "video",
    "themeName": "Seeing and making things that move",
    "blueprint": "Video Temporal Repo Lab",
    "paperTitle": "PAM: A Pose-Appearance-Motion Engine for Sim-to-Real HOI Video Generation",
    "repo": "flux",
    "repoUrl": "https://github.com/black-forest-labs/flux",
    "subthemes": [
      "video-generation",
      "hand-object-interaction",
      "sim-to-real",
      "diffusion",
      "controllable-generation",
      "embodied-AI"
    ],
    "problem": "PAM is about generating realistic hand-object interaction videos from simulator-accessible inputs. The everyday problem is turning initial and target hand-object poses into a photorealistic video without having a real first frame.",
    "jobId": "video-01-github-com-black-forest-labs-flu",
    "promotedEvidence": true,
    "readiness": 47,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-video-flux-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-video-flux-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job video-01-github-com-black-forest-labs-flu",
    "status": "demo-linked"
  },
  {
    "rank": 12,
    "theme": "video",
    "themeName": "Seeing and making things that move",
    "blueprint": "Video Temporal Repo Lab",
    "paperTitle": "Preserving Source Video Realism: High-Fidelity Face Swapping for Cinematic Quality",
    "repo": "face-",
    "repoUrl": "https://github.com/deepfakes/face-",
    "subthemes": [
      "face swapping",
      "video editing",
      "video generation",
      "diffusion models",
      "video synthesis",
      "face manipulation"
    ],
    "problem": "This paper is about cinematic-quality face swapping. The everyday problem is that swapping identity can break lighting, expression, skin detail, or camera realism from the source video.",
    "jobId": "video-02-github-com-deepfakes-face",
    "promotedEvidence": true,
    "readiness": 46,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-video-temporal-repo-lab.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job video-02-github-com-deepfakes-face",
    "status": "demo-linked"
  },
  {
    "rank": 13,
    "theme": "video",
    "themeName": "Seeing and making things that move",
    "blueprint": "Video Temporal Repo Lab",
    "paperTitle": "Back to the Feature: Explaining Video Classifiers with Video Counterfactual Explanations",
    "repo": "DiffSynth-",
    "repoUrl": "https://github.com/modelscope/DiffSynth-",
    "subthemes": [
      "diffusion",
      "video-generation",
      "explainability",
      "counterfactual",
      "video-classification",
      "interpretability"
    ],
    "problem": "This paper is about explaining video classifiers with counterfactual videos. The everyday problem is that to explain why a model saw running instead of walking, the changed video must still look smooth and physically believable.",
    "jobId": "video-03-github-com-modelscope-diffsynth",
    "promotedEvidence": true,
    "readiness": 36,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-video-temporal-repo-lab.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job video-03-github-com-modelscope-diffsynth",
    "status": "demo-linked"
  },
  {
    "rank": 14,
    "theme": "video",
    "themeName": "Seeing and making things that move",
    "blueprint": "Video Temporal Repo Lab",
    "paperTitle": "AdaSpot: Spend Resolution Where It Matters for Precise Event Spotting",
    "repo": "AdaSpot",
    "repoUrl": "https://github.com/arturxe2/AdaSpot",
    "subthemes": [
      "event spotting",
      "temporal action detection",
      "spatial attention",
      "video efficiency",
      "dynamic computation",
      "precise localization"
    ],
    "problem": "AdaSpot is about finding the exact moment of an event in video while spending high resolution only where it helps. The everyday problem is that a decisive action may happen in a small region, while most of the frame is irrelevant background.",
    "jobId": "video-04-github-com-arturxe2-adaspot",
    "promotedEvidence": true,
    "readiness": 51,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-video-temporal-repo-lab.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job video-04-github-com-arturxe2-adaspot",
    "status": "demo-linked"
  },
  {
    "rank": 15,
    "theme": "video",
    "themeName": "Seeing and making things that move",
    "blueprint": "Video Temporal Repo Lab",
    "paperTitle": "Hierarchical Action Learning for Weakly-Supervised Action Segmentation",
    "repo": "HAL",
    "repoUrl": "https://github.com/DMIRLAB-Group/HAL",
    "subthemes": [
      "action segmentation",
      "weakly-supervised",
      "hierarchical learning",
      "causal models",
      "temporal modeling",
      "identifiability"
    ],
    "problem": "Hierarchical Action Learning is about segmenting actions in video from only ordered transcripts, not timestamps. The everyday problem is that the model knows the action order but must infer where each action starts and ends.",
    "jobId": "video-05-github-com-dmirlab-group-hal",
    "promotedEvidence": true,
    "readiness": 42,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-video-temporal-repo-lab.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job video-05-github-com-dmirlab-group-hal",
    "status": "demo-linked"
  },
  {
    "rank": 16,
    "theme": "generation",
    "themeName": "Making pixels from meaning",
    "blueprint": "Generation Control Repo Studio",
    "paperTitle": "GDPO-SR: Group Direct Preference Optimization for One-Step Generative Image Super-Resolution",
    "repo": "GDPO",
    "repoUrl": "https://github.com/Joyies/GDPO",
    "subthemes": [
      "super-resolution",
      "image-restoration",
      "reinforcement-learning",
      "diffusion",
      "dpo",
      "grpo"
    ],
    "problem": "GDPO-SR is about one-step image super-resolution that still preserves fine local texture. The everyday problem is enlarging a low-resolution image while making smooth regions clean and textured regions sharp.",
    "jobId": "generation-01-github-com-joyies-gdpo",
    "promotedEvidence": true,
    "readiness": 37,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-generation-gdpo-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-generation-gdpo-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-01-github-com-joyies-gdpo",
    "status": "demo-linked"
  },
  {
    "rank": 17,
    "theme": "generation",
    "themeName": "Making pixels from meaning",
    "blueprint": "Generation Control Repo Studio",
    "paperTitle": "Bridging Fidelity-Reality with Controllable One-Step Diffusion for Image Super-Resolution",
    "repo": "CODSR",
    "repoUrl": "https://github.com/Chanson94/CODSR",
    "subthemes": [
      "image super-resolution",
      "diffusion models",
      "one-step inference",
      "low-level vision",
      "text-guided generation",
      "fidelity-perceptual tradeoff"
    ],
    "problem": "CODSR is about one-step super-resolution that looks realistic without losing faithfulness to the low-quality input. The everyday problem is that generative priors can invent detail, but pure fidelity can leave images blurry.",
    "jobId": "generation-02-github-com-chanson94-codsr",
    "promotedEvidence": true,
    "readiness": 34,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-generation-control-repo-studio.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-02-github-com-chanson94-codsr",
    "status": "demo-linked"
  },
  {
    "rank": 18,
    "theme": "generation",
    "themeName": "Making pixels from meaning",
    "blueprint": "Generation Control Repo Studio",
    "paperTitle": "Resolving Endpoint Underfitting in Diffusion Bridges via Noise Alignment",
    "repo": "NADB",
    "repoUrl": "https://github.com/gyr02/NADB",
    "subthemes": [
      "diffusion",
      "image-restoration",
      "diffusion-bridge",
      "stochastic-interpolant",
      "super-resolution",
      "deblurring"
    ],
    "problem": "This diffusion-bridge paper is about fixing weak performance near the clean endpoint of an image-restoration path. The everyday problem is that a model can learn most of the journey from degraded to clean but still miss the final sharp correction at the target",
    "jobId": "generation-03-github-com-gyr02-nadb",
    "promotedEvidence": true,
    "readiness": 40,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-generation-control-repo-studio.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-03-github-com-gyr02-nadb",
    "status": "demo-linked"
  },
  {
    "rank": 19,
    "theme": "generation",
    "themeName": "Making pixels from meaning",
    "blueprint": "Generation Control Repo Studio",
    "paperTitle": "Low-Rank Residual Diffusion Models",
    "repo": "LRDM",
    "repoUrl": "https://github.com/JF-Tan/LRDM",
    "subthemes": [
      "diffusion-models",
      "image-restoration",
      "low-rank",
      "deraining",
      "deblurring",
      "deshading"
    ],
    "problem": "This paper is about restoration when the damaged image is already close to the desired image. The everyday problem is that standard diffusion wastes effort generating everything, even though only a small correction may be needed.",
    "jobId": "generation-04-github-com-jf-tan-lrdm",
    "promotedEvidence": true,
    "readiness": 38,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-generation-control-repo-studio.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-04-github-com-jf-tan-lrdm",
    "status": "demo-linked"
  },
  {
    "rank": 20,
    "theme": "generation",
    "themeName": "Making pixels from meaning",
    "blueprint": "Generation Control Repo Studio",
    "paperTitle": "Residual Diffusion Bridge Model for Image Restoration",
    "repo": "RDBM",
    "repoUrl": "https://github.com/MiliLab/RDBM",
    "subthemes": [
      "diffusion-models",
      "image-restoration",
      "universal-restoration",
      "stochastic-differential-equations",
      "residual-learning",
      "adaptive-processing"
    ],
    "problem": "This paper is about restoring damaged images without disturbing clean regions. The everyday problem is that a restoration model should repair degradation locally rather than repaint the entire image.",
    "jobId": "generation-05-github-com-mililab-rdbm",
    "promotedEvidence": true,
    "readiness": 33,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-generation-control-repo-studio.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-05-github-com-mililab-rdbm",
    "status": "demo-linked"
  },
  {
    "rank": 21,
    "theme": "vlm",
    "themeName": "Teaching machines to see and talk at once",
    "blueprint": "Grounded VLM Repo Court",
    "paperTitle": "FedAFD: Multimodal Federated Learning via Adversarial Fusion and Distillation",
    "repo": "FedAFD",
    "repoUrl": "https://github.com/Chao2433/FedAFD",
    "subthemes": [
      "federated-learning",
      "multimodal",
      "privacy-preserving",
      "knowledge-distillation",
      "adversarial-learning",
      "feature-fusion"
    ],
    "problem": "FedAFD is about federated learning across clients with different modalities, tasks, and model shapes. The everyday problem is letting participants collaborate when their local evidence and architectures do not match.",
    "jobId": "vlm-01-github-com-chao2433-fedafd",
    "promotedEvidence": true,
    "readiness": 46,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-vlm-fedafd-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-vlm-fedafd-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job vlm-01-github-com-chao2433-fedafd",
    "status": "demo-linked"
  },
  {
    "rank": 22,
    "theme": "vlm",
    "themeName": "Teaching machines to see and talk at once",
    "blueprint": "Grounded VLM Repo Court",
    "paperTitle": "Towards Cross-Modal Preservation, Consistency and Alignment for Privacy-Preserving Visible-Infrared Person Re-Identification",
    "repo": "PPA_CVPR26",
    "repoUrl": "https://github.com/Dige945/PPA_CVPR26",
    "subthemes": [
      "person-re-identification",
      "privacy-preservation",
      "cross-modal-matching",
      "visible-infrared",
      "anonymization",
      "keypoint-preservation"
    ],
    "problem": "This privacy-preserving visible-infrared person re-identification work is about recognizing the same person across day and night cameras while hiding private appearance details. The everyday problem is that anonymization can erase the very body structure neede",
    "jobId": "vlm-02-github-com-dige945-ppa-cvpr26",
    "promotedEvidence": true,
    "readiness": 48,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-grounded-vlm-repo-court.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job vlm-02-github-com-dige945-ppa-cvpr26",
    "status": "demo-linked"
  },
  {
    "rank": 23,
    "theme": "vlm",
    "themeName": "Teaching machines to see and talk at once",
    "blueprint": "Grounded VLM Repo Court",
    "paperTitle": "GraphVLM: Benchmarking Vision Language Models for Multimodal Graph Learning",
    "repo": "GraphVLM",
    "repoUrl": "https://github.com/oamyjin/GraphVLM",
    "subthemes": [
      "vision-language-models",
      "graph-learning",
      "multimodal",
      "graph-neural-networks",
      "benchmark",
      "graph-reasoning"
    ],
    "problem": "GraphVLM is about testing how vision-language models handle graph-structured multimodal data. The everyday problem is reasoning about nodes and links when each entity may also have images and text.",
    "jobId": "vlm-03-github-com-oamyjin-graphvlm",
    "promotedEvidence": true,
    "readiness": 43,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-grounded-vlm-repo-court.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job vlm-03-github-com-oamyjin-graphvlm",
    "status": "demo-linked"
  },
  {
    "rank": 24,
    "theme": "vlm",
    "themeName": "Teaching machines to see and talk at once",
    "blueprint": "Grounded VLM Repo Court",
    "paperTitle": "ReCALL: Recalibrating Capability Degradation for MLLM-based Composed Image Retrieval",
    "repo": "Recall",
    "repoUrl": "https://github.com/RemRico/Recall",
    "subthemes": [
      "composed image retrieval",
      "multimodal reasoning",
      "vision-language models",
      "contrastive learning",
      "capability preservation",
      "cross-modal alignment"
    ],
    "problem": "ReCALL is about preserving multimodal reasoning when adapting an MLLM to composed image retrieval. The everyday problem is that compressing a reasoning model into one retrieval embedding can erase fine relations like red bag on the left but with a different st",
    "jobId": "vlm-04-github-com-remrico-recall",
    "promotedEvidence": true,
    "readiness": 34,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-grounded-vlm-repo-court.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job vlm-04-github-com-remrico-recall",
    "status": "demo-linked"
  },
  {
    "rank": 25,
    "theme": "vlm",
    "themeName": "Teaching machines to see and talk at once",
    "blueprint": "Grounded VLM Repo Court",
    "paperTitle": "See It, Say It, Sorted: An Iterative Training-Free Framework for Visually-Grounded Multimodal Reasoning in LVLMs",
    "repo": "See-It-Say-It-Sorted",
    "repoUrl": "https://github.com/uuuuZYC/See-It-Say-It-Sorted",
    "subthemes": [
      "chain-of-thought",
      "hallucination mitigation",
      "visual grounding",
      "LVLMs",
      "reasoning",
      "test-time inference"
    ],
    "problem": "See It Say It Sorted is about improving multimodal answers without new training. The everyday problem is that a model may generate fluent but weakly grounded reasoning unless it repeatedly checks visible evidence.",
    "jobId": "vlm-05-github-com-uuuuzyc-see-it-say-it",
    "promotedEvidence": true,
    "readiness": 46,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-grounded-vlm-repo-court.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job vlm-05-github-com-uuuuzyc-see-it-say-it",
    "status": "demo-linked"
  },
  {
    "rank": 26,
    "theme": "perceive",
    "themeName": "Naming and locating what's in the picture",
    "blueprint": "Perception Parts Repo Bench",
    "paperTitle": "Focus on Background: Exploring SAM's Potential in Few-shot Medical Image Segmentation",
    "repo": "FoB",
    "repoUrl": "https://github.com/primebo1/FoB",
    "subthemes": [
      "few-shot segmentation",
      "medical imaging",
      "SAM",
      "background prompting",
      "GCN",
      "graph neural network"
    ],
    "problem": "This few-shot medical segmentation work is about using background cues, not only foreground prompts. The everyday problem is that two medical structures may look similar, and the surrounding tissue can be the clue that separates the target from lookalikes.",
    "jobId": "perception-01-github-com-primebo1-fob",
    "promotedEvidence": true,
    "readiness": 51,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-perception-fob-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-perception-fob-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job perception-01-github-com-primebo1-fob",
    "status": "demo-linked"
  },
  {
    "rank": 27,
    "theme": "perceive",
    "themeName": "Naming and locating what's in the picture",
    "blueprint": "Perception Parts Repo Bench",
    "paperTitle": "Denoise and Align: Towards Source-Free UDA for Robust Panoramic Semantic Segmentation",
    "repo": "DAPASS",
    "repoUrl": "https://github.com/ZZZPhaethon/DAPASS",
    "subthemes": [
      "panoramic-segmentation",
      "domain-adaptation",
      "semantic-segmentation",
      "source-free",
      "equirectangular-projection",
      "autonomous-driving"
    ],
    "problem": "DAPASS is about adapting a segmentation model to panoramic 360-degree images without source training data. The everyday problem is that panoramic projection distorts scale and shape, while noisy pseudo-labels can lock the adapted model into wrong classes.",
    "jobId": "perception-02-github-com-zzzphaethon-dapass",
    "promotedEvidence": true,
    "readiness": 46,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-perception-parts-repo-bench.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job perception-02-github-com-zzzphaethon-dapass",
    "status": "demo-linked"
  },
  {
    "rank": 28,
    "theme": "perceive",
    "themeName": "Naming and locating what's in the picture",
    "blueprint": "Perception Parts Repo Bench",
    "paperTitle": "TF-SSD: A Strong Pipeline via Synergic Mask Filter for Training-free Co-Salient Object Detection",
    "repo": "TF-SSD",
    "repoUrl": "https://github.com/hzz-yy/TF-SSD",
    "subthemes": [
      "co-salient-object-detection",
      "training-free",
      "zero-shot",
      "SAM",
      "DINO",
      "segmentation"
    ],
    "problem": "TF-SSD is about detecting common salient objects across image groups without labeled training. The everyday problem is that zero-shot mask proposals are noisy, and the system must find which masks point to the same meaningful object across images.",
    "jobId": "perception-03-github-com-hzz-yy-tf-ssd",
    "promotedEvidence": true,
    "readiness": 49,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-perception-parts-repo-bench.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job perception-03-github-com-hzz-yy-tf-ssd",
    "status": "demo-linked"
  },
  {
    "rank": 29,
    "theme": "perceive",
    "themeName": "Naming and locating what's in the picture",
    "blueprint": "Perception Parts Repo Bench",
    "paperTitle": "TAPE: Task-Adaptive Prototype Evolution in Audio-Language Models for Fully Few-Shot Class-Incremental Audio Classification",
    "repo": "TAPE",
    "repoUrl": "https://github.com/YvoGao/TAPE",
    "subthemes": [
      "audio classification",
      "few-shot learning",
      "class-incremental learning",
      "continual learning",
      "CLAP",
      "audio-language model"
    ],
    "problem": "TAPE is about learning new audio classes from a few examples without forgetting old ones. The everyday problem is that a new sound category may have only a handful of clips, and the original training audio may no longer be available.",
    "jobId": "perception-04-github-com-yvogao-tape",
    "promotedEvidence": true,
    "readiness": 57,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-perception-parts-repo-bench.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job perception-04-github-com-yvogao-tape",
    "status": "demo-linked"
  },
  {
    "rank": 30,
    "theme": "perceive",
    "themeName": "Naming and locating what's in the picture",
    "blueprint": "Perception Parts Repo Bench",
    "paperTitle": "EReCu: Pseudo-label Evolution Fusion and Refinement with Multi-Cue Learning for Unsupervised Camouflage Detection",
    "repo": "EReCu",
    "repoUrl": "https://github.com/JSLiam94/EReCu",
    "subthemes": [
      "camouflaged-object-detection",
      "unsupervised",
      "pseudo-labels",
      "teacher-student",
      "segmentation",
      "detail-preservation"
    ],
    "problem": "EReCu is about finding camouflaged objects without clean labels. The everyday problem is that the object is designed by nature or texture to look like its background, so noisy pseudo-labels can either spill past the boundary or erase fine detail.",
    "jobId": "perception-05-github-com-jsliam94-erecu",
    "promotedEvidence": true,
    "readiness": 37,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-perception-parts-repo-bench.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job perception-05-github-com-jsliam94-erecu",
    "status": "demo-linked"
  },
  {
    "rank": 31,
    "theme": "embodied",
    "themeName": "Using vision to act in the world",
    "blueprint": "Embodied Control Repo Drill",
    "paperTitle": "Reliable Policy Transfer for Safety-Aware End-to-End Driving with Deep Reinforcement Learning",
    "repo": "safe-driving-drl",
    "repoUrl": "https://github.com/szu-ai/safe-driving-drl",
    "subthemes": [
      "autonomous driving",
      "reinforcement learning",
      "policy transfer",
      "uncertainty estimation",
      "CARLA",
      "SAC"
    ],
    "problem": "This driving work is about transferring a reinforcement-learned policy safely across towns and weather. The everyday problem is that a car policy can behave well in one simulator setting but become brittle when uncertainty, road layout, or traffic interactions",
    "jobId": "embodied-01-github-com-szu-ai-safe-driving-d",
    "promotedEvidence": true,
    "readiness": 57,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-embodied-safe-driving-drl-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-embodied-safe-driving-drl-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job embodied-01-github-com-szu-ai-safe-driving-d",
    "status": "demo-linked"
  },
  {
    "rank": 32,
    "theme": "embodied",
    "themeName": "Using vision to act in the world",
    "blueprint": "Embodied Control Repo Drill",
    "paperTitle": "Saliency-Guided Representation with Consistency Policy Learning for Visual Unsupervised Reinforcement Learning",
    "repo": "SRCP",
    "repoUrl": "https://github.com/bofusun/SRCP",
    "subthemes": [
      "unsupervised-reinforcement-learning",
      "visual-control",
      "skill-learning",
      "representation-learning",
      "zero-shot-generalization",
      "consistency-models"
    ],
    "problem": "This paper is about unsupervised reinforcement learning from vision. The everyday problem is that an agent must learn useful behavior without rewards, so it needs to focus on visually important parts of the scene.",
    "jobId": "embodied-02-github-com-bofusun-srcp",
    "promotedEvidence": true,
    "readiness": 51,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-embodied-control-repo-drill.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job embodied-02-github-com-bofusun-srcp",
    "status": "demo-linked"
  },
  {
    "rank": 33,
    "theme": "embodied",
    "themeName": "Using vision to act in the world",
    "blueprint": "Embodied Control Repo Drill",
    "paperTitle": "EnergyAction: Unimanual to Bimanual Composition with Energy-Based Models",
    "repo": "EnergyAction",
    "repoUrl": "https://github.com/codeshop715/EnergyAction",
    "subthemes": [
      "robotics",
      "manipulation",
      "energy-based models",
      "policy transfer",
      "bimanual control",
      "compositional learning"
    ],
    "problem": "EnergyAction is about composing one-hand actions into two-hand actions. The everyday problem is that two hands must coordinate, not just duplicate independent motions.",
    "jobId": "embodied-03-github-com-codeshop715-energyact",
    "promotedEvidence": true,
    "readiness": 54,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-embodied-control-repo-drill.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job embodied-03-github-com-codeshop715-energyact",
    "status": "demo-linked"
  },
  {
    "rank": 34,
    "theme": "embodied",
    "themeName": "Using vision to act in the world",
    "blueprint": "Embodied Control Repo Drill",
    "paperTitle": "Dynamic Important Example Mining for Reinforcement Finetuning",
    "repo": "DIEM",
    "repoUrl": "https://github.com/hrtan/DIEM",
    "subthemes": [
      "reinforcement-learning",
      "fine-tuning",
      "data-selection",
      "curriculum-learning",
      "policy-optimization",
      "sample-importance"
    ],
    "problem": "The paper is about choosing which training examples matter right now. The everyday problem is that a lesson that was useful yesterday may be too easy or misleading after the learner changes.",
    "jobId": "embodied-04-github-com-hrtan-diem",
    "promotedEvidence": true,
    "readiness": 59,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-embodied-control-repo-drill.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job embodied-04-github-com-hrtan-diem",
    "status": "demo-linked"
  },
  {
    "rank": 35,
    "theme": "embodied",
    "themeName": "Using vision to act in the world",
    "blueprint": "Embodied Control Repo Drill",
    "paperTitle": "HiconAgent: History Context-aware Policy Optimization for GUI Agents",
    "repo": "HiconAgent",
    "repoUrl": "https://github.com/JiuTian-VL/HiconAgent",
    "subthemes": [
      "gui-agents",
      "policy-optimization",
      "history-awareness",
      "task-automation",
      "reinforcement-learning"
    ],
    "problem": "HiconAgent is about GUI agents that remember what they already did. The everyday problem is that a screen action only makes sense in the context of previous clicks, fields, dialogs, and state changes.",
    "jobId": "embodied-05-github-com-jiutian-vl-hiconagent",
    "promotedEvidence": true,
    "readiness": 61,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-embodied-control-repo-drill.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job embodied-05-github-com-jiutian-vl-hiconagent",
    "status": "demo-linked"
  },
  {
    "rank": 36,
    "theme": "learning",
    "themeName": "Learning more from less, and not breaking",
    "blueprint": "Efficient Learning Repo Governor",
    "paperTitle": "What Do Visual Tokens Really Encode: Uncovering Sparsity and Redundancy",
    "repo": "EmbedLens",
    "repoUrl": "https://github.com/EIT-NLP/EmbedLens",
    "subthemes": [
      "vision-transformers",
      "token-analysis",
      "model-compression",
      "network-pruning",
      "interpretability"
    ],
    "problem": "What Do Visual Tokens Really Encode is about finding which image patches in a transformer actually carry useful information. The everyday problem is that a model may spend equal effort on sky, wall, object edge, and repeated texture even though many tokens say",
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "promotedEvidence": true,
    "readiness": 57,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "first",
    "demoPage": "cvpr-learning-embedlens-deep-viewer.html",
    "wavePage": "cvpr-interactive-demo-workbench.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": true,
    "deepViewerPage": "cvpr-learning-embedlens-deep-viewer.html",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-01-github-com-eit-nlp-embedlens",
    "status": "demo-linked"
  },
  {
    "rank": 37,
    "theme": "learning",
    "themeName": "Learning more from less, and not breaking",
    "blueprint": "Efficient Learning Repo Governor",
    "paperTitle": "NuWa: Deriving Lightweight Class-Specific Vision Transformers for Edge Devices",
    "repo": "NuWa",
    "repoUrl": "https://github.com/CGCL-codes/NuWa",
    "subthemes": [
      "vision transformer",
      "model compression",
      "pruning",
      "edge devices",
      "structured pruning",
      "knowledge distillation"
    ],
    "problem": "NuWa is about shrinking vision transformers for edge devices. The everyday problem is that an edge camera may only need a few object classes, so carrying a full general model wastes memory and power.",
    "jobId": "learning-02-github-com-cgcl-codes-nuwa",
    "promotedEvidence": true,
    "readiness": 57,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "second",
    "demoPage": "cvpr-efficient-learning-repo-governor.html",
    "wavePage": "cvpr-interactive-second-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-02-github-com-cgcl-codes-nuwa",
    "status": "demo-linked"
  },
  {
    "rank": 38,
    "theme": "learning",
    "themeName": "Learning more from less, and not breaking",
    "blueprint": "Efficient Learning Repo Governor",
    "paperTitle": "FOZO: Forward-Only Zeroth-Order Prompt Optimization for Test-Time Adaptation",
    "repo": "FOZO",
    "repoUrl": "https://github.com/eVI-group-SCU/FOZO",
    "subthemes": [
      "test-time-adaptation",
      "domain-adaptation",
      "zeroth-order-optimization",
      "prompt-tuning",
      "vision-transformer",
      "forward-only-learning"
    ],
    "problem": "FOZO is about adapting a model at test time on devices that cannot afford backpropagation. The everyday problem is that the model faces a shifted environment, but computing full gradients is too expensive in memory and time.",
    "jobId": "learning-03-github-com-evi-group-scu-fozo",
    "promotedEvidence": true,
    "readiness": 45,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "third",
    "demoPage": "cvpr-efficient-learning-repo-governor.html",
    "wavePage": "cvpr-interactive-third-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-03-github-com-evi-group-scu-fozo",
    "status": "demo-linked"
  },
  {
    "rank": 39,
    "theme": "learning",
    "themeName": "Learning more from less, and not breaking",
    "blueprint": "Efficient Learning Repo Governor",
    "paperTitle": "CHEEM: Continual Learning by Reuse, New, Adapt and Skip \u2013 A Hierarchical Exploration-Exploitation Approach",
    "repo": "cheem",
    "repoUrl": "https://github.com/savadikarc/cheem",
    "subthemes": [
      "continual-learning",
      "class-incremental",
      "neural-architecture-search",
      "vision-transformers",
      "dynamic-architecture",
      "task-adaptation"
    ],
    "problem": "CHEEM is about deciding how a continual learner should change its architecture for each new task. The everyday problem is that some tasks should reuse old knowledge, some need new capacity, some need adaptation, and some parts should be skipped.",
    "jobId": "learning-04-github-com-savadikarc-cheem",
    "promotedEvidence": true,
    "readiness": 43,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fourth",
    "demoPage": "cvpr-efficient-learning-repo-governor.html",
    "wavePage": "cvpr-interactive-fourth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-04-github-com-savadikarc-cheem",
    "status": "demo-linked"
  },
  {
    "rank": 40,
    "theme": "learning",
    "themeName": "Learning more from less, and not breaking",
    "blueprint": "Efficient Learning Repo Governor",
    "paperTitle": "Towards Stable Federated Continual Test-Time Adaptation in Wild World",
    "repo": "BPFedCTTA",
    "repoUrl": "https://github.com/LiwenWang919/BPFedCTTA",
    "subthemes": [
      "federated-learning",
      "test-time-adaptation",
      "continual-learning",
      "bayesian-inference",
      "domain-adaptation",
      "uncertainty-quantification"
    ],
    "problem": "This paper is about adapting federated models to changing unlabeled client data. The everyday problem is that each client sees shifts at different times, and noisy test-time updates can destabilize the shared model.",
    "jobId": "learning-05-github-com-liwenwang919-bpfedctt",
    "promotedEvidence": true,
    "readiness": 39,
    "accelerator": "A100",
    "interactiveReady": true,
    "wave": "fifth",
    "demoPage": "cvpr-efficient-learning-repo-governor.html",
    "wavePage": "cvpr-interactive-fifth-wave.html",
    "controls": 5,
    "artifactCount": 3,
    "deepViewerReady": false,
    "deepViewerPage": "",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-05-github-com-liwenwang919-bpfedctt",
    "status": "demo-linked"
  }
];
export const summary = {
  "matrix": "cvpr-top-paper-repo-demo-matrix",
  "status": "matrix-ready",
  "sourceForge": "analysis/cvpr_paper_repo_demo_forge/registry.json",
  "sourcePromotedResults": "analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json",
  "sourceInteractiveCoverage": "analysis/cvpr_interactive_coverage_portfolio/registry.json",
  "sourceDeepViewers": "analysis/cvpr_deep_viewer_portfolio/registry.json",
  "topPaperRepos": 40,
  "readyRows": 40,
  "themes": 8,
  "blueprints": 8,
  "subthemeTags": 237,
  "promotedEvidenceRows": 40,
  "interactiveRows": 40,
  "deepViewerRows": 8,
  "artifacts": 120,
  "controls": 200,
  "coverageDemos": 40,
  "coverageWaves": 5,
  "deepViewerPortfolioRows": 8,
  "holds": 0,
  "validator": "scripts/verify_cvpr_top_paper_repo_demo_matrix.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
