export const stages = [
  {
    "system": "open-vocab-visual-search",
    "systemTitle": "Open-vocabulary visual search",
    "stage": "text-query-grounding",
    "stageTitle": "Ground text queries in visible regions",
    "theme": "Naming and locating what's in the picture",
    "themeSlug": "perceive",
    "cluster": "Open-vocabulary vision",
    "clusterSlug": "open_vocab",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "reject answers without localized evidence",
    "reusableRule": "Open-vocabulary visual search stage 'Ground text queries in visible regions' should reject answers without localized evidence using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "open-vocab-visual-search",
    "systemTitle": "Open-vocabulary visual search",
    "stage": "long-tail-retrieval",
    "stageTitle": "Retrieve long-tail objects",
    "theme": "Naming and locating what's in the picture",
    "themeSlug": "perceive",
    "cluster": "Open-vocabulary vision",
    "clusterSlug": "open_vocab",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "rank rare concepts without collapsing to frequent labels",
    "reusableRule": "Open-vocabulary visual search stage 'Retrieve long-tail objects' should rank rare concepts without collapsing to frequent labels using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "open-vocab-visual-search",
    "systemTitle": "Open-vocabulary visual search",
    "stage": "evidence-inspection",
    "stageTitle": "Expose search evidence",
    "theme": "Naming and locating what's in the picture",
    "themeSlug": "perceive",
    "cluster": "Open-vocabulary vision",
    "clusterSlug": "open_vocab",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "show regions, uncertainty, and failure modes before trust",
    "reusableRule": "Open-vocabulary visual search stage 'Expose search evidence' should show regions, uncertainty, and failure modes before trust using measured CVPR evidence, not only paper novelty."
  }
];
