export const artifactRows = [
  {
    "jobId": "frontier-01-github-com-yjzhao1019-mos",
    "theme": "frontier",
    "repo": "MOS",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.json",
    "exists": true,
    "bytes": 599,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "frontier-01-github-com-yjzhao1019-mos",
    "theme": "frontier",
    "repo": "MOS",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.log",
    "exists": true,
    "bytes": 202,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "frontier-01-github-com-yjzhao1019-mos",
    "theme": "frontier",
    "repo": "MOS",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.snapshot.json",
    "exists": true,
    "bytes": 300,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "threed-01-github-com-deepinsight-insightfa",
    "theme": "threed",
    "repo": "insightface",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.json",
    "exists": true,
    "bytes": 619,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "threed-01-github-com-deepinsight-insightfa",
    "theme": "threed",
    "repo": "insightface",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.log",
    "exists": true,
    "bytes": 216,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "threed-01-github-com-deepinsight-insightfa",
    "theme": "threed",
    "repo": "insightface",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.snapshot.json",
    "exists": true,
    "bytes": 314,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "video-01-github-com-black-forest-labs-flu",
    "theme": "video",
    "repo": "flux",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.json",
    "exists": true,
    "bytes": 609,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "video-01-github-com-black-forest-labs-flu",
    "theme": "video",
    "repo": "flux",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.log",
    "exists": true,
    "bytes": 214,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "video-01-github-com-black-forest-labs-flu",
    "theme": "video",
    "repo": "flux",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.snapshot.json",
    "exists": true,
    "bytes": 312,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "generation-01-github-com-joyies-gdpo",
    "theme": "generation",
    "repo": "GDPO",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.json",
    "exists": true,
    "bytes": 598,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "generation-01-github-com-joyies-gdpo",
    "theme": "generation",
    "repo": "GDPO",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.log",
    "exists": true,
    "bytes": 198,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "generation-01-github-com-joyies-gdpo",
    "theme": "generation",
    "repo": "GDPO",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.snapshot.json",
    "exists": true,
    "bytes": 296,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "vlm-01-github-com-chao2433-fedafd",
    "theme": "vlm",
    "repo": "FedAFD",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.json",
    "exists": true,
    "bytes": 594,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "vlm-01-github-com-chao2433-fedafd",
    "theme": "vlm",
    "repo": "FedAFD",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.log",
    "exists": true,
    "bytes": 199,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "vlm-01-github-com-chao2433-fedafd",
    "theme": "vlm",
    "repo": "FedAFD",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.snapshot.json",
    "exists": true,
    "bytes": 297,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "perception-01-github-com-primebo1-fob",
    "theme": "perception",
    "repo": "FoB",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.json",
    "exists": true,
    "bytes": 599,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "perception-01-github-com-primebo1-fob",
    "theme": "perception",
    "repo": "FoB",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.log",
    "exists": true,
    "bytes": 200,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "perception-01-github-com-primebo1-fob",
    "theme": "perception",
    "repo": "FoB",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.snapshot.json",
    "exists": true,
    "bytes": 298,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "embodied-01-github-com-szu-ai-safe-driving-d",
    "theme": "embodied",
    "repo": "safe-driving-drl",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.json",
    "exists": true,
    "bytes": 628,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "embodied-01-github-com-szu-ai-safe-driving-d",
    "theme": "embodied",
    "repo": "safe-driving-drl",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.log",
    "exists": true,
    "bytes": 218,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "embodied-01-github-com-szu-ai-safe-driving-d",
    "theme": "embodied",
    "repo": "safe-driving-drl",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.snapshot.json",
    "exists": true,
    "bytes": 316,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "theme": "learning",
    "repo": "EmbedLens",
    "kind": "smokeJson",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.json",
    "exists": true,
    "bytes": 611,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "theme": "learning",
    "repo": "EmbedLens",
    "kind": "log",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.log",
    "exists": true,
    "bytes": 208,
    "status": "rehydrated",
    "source": "promoted-results-json"
  },
  {
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "theme": "learning",
    "repo": "EmbedLens",
    "kind": "repoSnapshot",
    "path": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.snapshot.json",
    "exists": true,
    "bytes": 306,
    "status": "rehydrated",
    "source": "promoted-results-json"
  }
];
export const summary = {
  "queue": "cvpr-artifact-rehydration-queue",
  "status": "rehydrated",
  "sourceGallery": "analysis/cvpr_reproduction_viewer_gallery/registry.json",
  "sourcePromotedResults": "analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json",
  "jobs": 8,
  "themes": 8,
  "artifacts": 24,
  "rehydratedArtifacts": 24,
  "missingArtifacts": 0,
  "validator": "scripts/verify_cvpr_artifact_rehydration_queue.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
