export const portfolioRows = [
  {
    "viewer": "cvpr-frontier-mos-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "MOS",
    "jobId": "frontier-01-github-com-yjzhao1019-mos",
    "theme": "frontier",
    "page": "cvpr-frontier-mos-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-threed-insightface-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "insightface",
    "jobId": "threed-01-github-com-deepinsight-insightfa",
    "theme": "threed",
    "page": "cvpr-threed-insightface-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-video-flux-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "flux",
    "jobId": "video-01-github-com-black-forest-labs-flu",
    "theme": "video",
    "page": "cvpr-video-flux-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-generation-gdpo-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "GDPO",
    "jobId": "generation-01-github-com-joyies-gdpo",
    "theme": "generation",
    "page": "cvpr-generation-gdpo-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-vlm-fedafd-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "FedAFD",
    "jobId": "vlm-01-github-com-chao2433-fedafd",
    "theme": "vlm",
    "page": "cvpr-vlm-fedafd-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-perception-fob-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "FoB",
    "jobId": "perception-01-github-com-primebo1-fob",
    "theme": "perception",
    "page": "cvpr-perception-fob-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-embodied-safe-driving-drl-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "safe-driving-drl",
    "jobId": "embodied-01-github-com-szu-ai-safe-driving-d",
    "theme": "embodied",
    "page": "cvpr-embodied-safe-driving-drl-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  },
  {
    "viewer": "cvpr-learning-embedlens-deep-viewer",
    "status": "deep-viewer-ready",
    "repo": "EmbedLens",
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "theme": "learning",
    "page": "cvpr-learning-embedlens-deep-viewer.html",
    "panels": 5,
    "readyPanels": 5,
    "selectedPanel": "output",
    "promotedEvidenceRows": 1,
    "artifacts": 3,
    "artifactLocalPaths": 3,
    "artifactMissingPaths": 0,
    "smokePassed": true,
    "accelerator": "A100"
  }
];
export const summary = {
  "portfolio": "cvpr-deep-viewer-portfolio",
  "status": "portfolio-ready",
  "sourceGallery": "analysis/cvpr_reproduction_viewer_gallery/registry.json",
  "sourcePromotedResults": "analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json",
  "deepViewers": 8,
  "readyDeepViewers": 8,
  "themes": 8,
  "pages": 8,
  "panels": 40,
  "readyPanels": 40,
  "artifacts": 24,
  "artifactLocalPaths": 24,
  "artifactMissingPaths": 0,
  "holdViewers": 0,
  "validator": "scripts/verify_cvpr_deep_viewer_portfolio.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
