export const governorRows = [
  {
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "caseId": "token-redundancy-audit",
    "scenario": "Token sparsity saliency audit",
    "repo": "https://github.com/EIT-NLP/EmbedLens",
    "mode": "live-colab",
    "page": "cvpr-efficient-learning-repo-governor.html",
    "paperTitle": "What Do Visual Tokens Really Encode: Uncovering Sparsity and Redundancy",
    "baseDecision": "canary",
    "efficiencyRisk": 70.7,
    "liveReadiness": 57,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.json",
    "artifactQuestion": "Does the promoted run provide enough repo evidence to inspect sparse-token coverage before serving savings are trusted?",
    "efficiencyProbe": "saliency preservation under visual token sparsity",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-01-github-com-eit-nlp-embedlens",
    "evidenceScore": 100,
    "decision": "canary-demo"
  },
  {
    "jobId": "learning-02-github-com-cgcl-codes-nuwa",
    "caseId": "class-specific-edge-vit",
    "scenario": "Pruning accuracy canary audit",
    "repo": "https://github.com/CGCL-codes/NuWa",
    "mode": "live-colab",
    "page": "cvpr-efficient-learning-repo-governor.html",
    "paperTitle": "NuWa: Deriving Lightweight Class-Specific Vision Transformers for Edge Devices",
    "baseDecision": "canary",
    "efficiencyRisk": 67.5,
    "liveReadiness": 57,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-02-github-com-cgcl-codes-nuwa.json",
    "artifactQuestion": "Does the live artifact support checking prune-ratio savings against accuracy regression?",
    "efficiencyProbe": "accuracy floor under structured pruning and edge memory pressure",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-02-github-com-cgcl-codes-nuwa",
    "evidenceScore": 100,
    "decision": "canary-demo"
  },
  {
    "jobId": "learning-03-github-com-evi-group-scu-fozo",
    "caseId": "forward-only-tta",
    "scenario": "Forward-only adaptation audit",
    "repo": "https://github.com/eVI-group-SCU/FOZO",
    "mode": "live-colab",
    "page": "cvpr-efficient-learning-repo-governor.html",
    "paperTitle": "FOZO: Forward-Only Zeroth-Order Prompt Optimization for Test-Time Adaptation",
    "baseDecision": "hold",
    "efficiencyRisk": 84.3,
    "liveReadiness": 45,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-03-github-com-evi-group-scu-fozo.json",
    "artifactQuestion": "Does the promoted result carry enough evidence to inspect forward-only adaptation without hidden backward updates?",
    "efficiencyProbe": "adaptation quality under forward-only update constraints",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-03-github-com-evi-group-scu-fozo",
    "evidenceScore": 93.9,
    "decision": "efficiency-review"
  },
  {
    "jobId": "learning-04-github-com-savadikarc-cheem",
    "caseId": "continual-architecture-router",
    "scenario": "Continual drift serving audit",
    "repo": "https://github.com/savadikarc/cheem",
    "mode": "live-colab",
    "page": "cvpr-efficient-learning-repo-governor.html",
    "paperTitle": "CHEEM: Continual Learning by Reuse, New, Adapt and Skip \u2013 A Hierarchical Exploration-Exploitation Approach",
    "baseDecision": "hold",
    "efficiencyRisk": 88.0,
    "liveReadiness": 43,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-04-github-com-savadikarc-cheem.json",
    "artifactQuestion": "Does the live row support checking serving behavior as client or domain drift accumulates?",
    "efficiencyProbe": "continual adaptation under domain-shift and client-drift pressure",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-04-github-com-savadikarc-cheem",
    "evidenceScore": 91.2,
    "decision": "efficiency-review"
  },
  {
    "jobId": "learning-05-github-com-liwenwang919-bpfedctt",
    "caseId": "federated-wild-tta",
    "scenario": "Federated CTTA budget audit",
    "repo": "https://github.com/LiwenWang919/BPFedCTTA",
    "mode": "live-colab",
    "page": "cvpr-efficient-learning-repo-governor.html",
    "paperTitle": "Towards Stable Federated Continual Test-Time Adaptation in Wild World",
    "baseDecision": "hold",
    "efficiencyRisk": 88.6,
    "liveReadiness": 39,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-05-github-com-liwenwang919-bpfedctt.json",
    "artifactQuestion": "Does the promoted artifact support evidence checks for federated test-time adaptation under tight communication budgets?",
    "efficiencyProbe": "federated continual test-time adaptation under bandwidth and drift limits",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-05-github-com-liwenwang919-bpfedctt",
    "evidenceScore": 87.1,
    "decision": "efficiency-review"
  }
];
export const summary = {
  "governor": "cvpr-efficient-learning-live-evidence-governor",
  "status": "ready",
  "theme": "learning",
  "rows": 5,
  "liveRows": 5,
  "smokePassed": 5,
  "artifacts": 5,
  "canaryDemo": 2,
  "efficiencyReview": 3,
  "holdDemo": 0,
  "minEvidenceScore": 87.1,
  "maxEfficiencyRisk": 88.6,
  "sourceLearningGovernor": "analysis/cvpr_efficient_learning_repo_governor/registry.json",
  "sourceCommandCenter": "analysis/cvpr_repo_harness_command_center/registry.json",
  "sourcePromotedResults": "analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json",
  "validator": "scripts/validate_cvpr_repo_harness_results.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
