export const stages = [
  {
    "system": "gaussian-splatting-platform",
    "systemTitle": "Gaussian Splatting platform",
    "stage": "splat-fit",
    "stageTitle": "Fit renderable splats",
    "theme": "Recovering the 3D world from flat pictures",
    "themeSlug": "threed",
    "cluster": "Gaussian Splatting",
    "clusterSlug": "gaussian_splatting",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "optimize scene storage for fast novel views",
    "reusableRule": "Gaussian Splatting platform stage 'Fit renderable splats' should optimize scene storage for fast novel views using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "gaussian-splatting-platform",
    "systemTitle": "Gaussian Splatting platform",
    "stage": "semantic-splats",
    "stageTitle": "Attach semantic labels",
    "theme": "Recovering the 3D world from flat pictures",
    "themeSlug": "threed",
    "cluster": "Gaussian Splatting",
    "clusterSlug": "gaussian_splatting",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "make splats searchable and editable by meaning",
    "reusableRule": "Gaussian Splatting platform stage 'Attach semantic labels' should make splats searchable and editable by meaning using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "gaussian-splatting-platform",
    "systemTitle": "Gaussian Splatting platform",
    "stage": "watermark-provenance",
    "stageTitle": "Track provenance",
    "theme": "Recovering the 3D world from flat pictures",
    "themeSlug": "threed",
    "cluster": "Gaussian Splatting",
    "clusterSlug": "gaussian_splatting",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "protect generated 3D assets with inspectable marks",
    "reusableRule": "Gaussian Splatting platform stage 'Track provenance' should protect generated 3D assets with inspectable marks using measured CVPR evidence, not only paper novelty."
  }
];
