import assert from "node:assert/strict";
import { ledgerRows, summary } from "../src/fixtures.js";
import { ledgerGate, ledgerReady, summarizeLedger } from "../src/core.js";

const derived = summarizeLedger(ledgerRows);
assert.equal(derived.stages, 7);
assert.equal(derived.readyStages, 5);
assert.equal(ledgerRows.filter(ledgerReady).length, 5);
assert.equal(summary.stages, 7);
assert.equal(summary.readyStages, 5);
assert.equal(summary.gauntletBlocks, 23);
assert.equal(summary.actionableRows, 53);
assert.equal(summary.clearedBlocks, 23);
assert.equal(summary.promote, 18);
assert.equal(summary.monitor, 35);
assert.equal(summary.canaryRollback, 0);
assert.equal(summary.rollbackDrills, 12);
assert.equal(summary.rehearsalMisses, 0);
assert.equal(summary.incidents, 7);
assert.equal(ledgerGate(summary), "inspect");
assert.equal(summary.status, "inspect");
console.log("ok cvpr-remediation-audit-ledger:", summary.readyStages, "stages ready");
