import assert from "node:assert/strict";
import { plannerInput, planRows, summary } from "../src/fixtures.js";
import { expectedResults, plannerGate, summarizePlanner, waveForJob } from "../src/core.js";

const derived = summarizePlanner({ ...plannerInput, planRows });
assert.equal(derived.status, "ready");
assert.equal(plannerGate(summary), "ready");
assert.equal(summary.runtimePlane, "google-colab-pro-plus");
assert.equal(summary.jobs, 10);
assert.equal(summary.waves, 3);
assert.equal(summary.expectedResults, 40);
assert.equal(summary.cachedResults, 40);
assert.equal(summary.colabCoveredBenches, 10);
assert.equal(summary.systemEvidenceCoveredBenches, 1);
assert.equal(summary.missingRuntimeEvidence, 0);
assert.equal(summary.releaseStatus, "release");
assert.equal(summary.operationsStatus, "ready");
assert.equal(planRows.length, 10);
assert.equal(expectedResults(planRows), 40);
assert.equal(waveForJob({ priority: 1 }), "wave-1-grounding-fidelity-provenance");
assert.equal(waveForJob({ priority: 6 }), "wave-2-temporal-clinical-serving");
assert.equal(waveForJob({ priority: 10 }), "wave-3-generation-driving-3d");
console.log("ok cvpr-colab-execution-planner:", summary.waves, "waves,", summary.expectedResults, "expected results");
