import assert from "node:assert/strict";
import { validationInput } from "../src/fixtures.js";
import { gateStatus, summarizeValidationCenter } from "../src/core.js";

const summary = summarizeValidationCenter(validationInput);
assert.equal(gateStatus(validationInput.fullStack, validationInput.promotionDelta), summary.status);
assert.equal(summary.status, summary.releaseGate ? "release" : "block");
assert.equal(summary.fullStackStatus, validationInput.fullStack.summary.status);
assert.equal(summary.workerJobs, 14);
assert.equal(summary.promotedRunners, 14);
assert.equal(summary.cachedResults, 56);
assert.equal(summary.importIssues, 0);
assert.equal(summary.promotionDeltaStatus, "release");
assert.equal(summary.promotionRegressions, 0);
assert.equal(summary.maxReadinessDrop, 0);
assert.equal(summary.validImportJobs, 14);
assert.ok(summary.packageTests >= 26);
assert.equal(summary.implementedBenches, 11);
assert.equal(summary.benchCases, 44);
assert.equal(summary.slowest.length, 5);
assert.equal(summary.releaseGate, summary.fullStackStatus === "valid");
console.log("ok cvpr-validation-center:", summary.status, summary.steps, "steps");
