export const failureRows = [
  {
    "id": "cvpr-driving-safety-bench/urban-cut-in",
    "bench": "cvpr-driving-safety-bench",
    "page": "cvpr-driving-safety-bench.html",
    "registry": "analysis/cvpr_driving_safety_bench/registry.json",
    "system": "driving-vla-release-gate",
    "cluster": "Driving and vision-language-action",
    "case": "Urban cut-in",
    "family": "safety risk",
    "metric": "risk",
    "metricValue": 33.6,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 75.3,
    "controls": {
      "hazardDensity": 48,
      "actorSpeed": 40,
      "occlusion": 10,
      "actionConfidence": 82
    },
    "metrics": {
      "sceneGrounding": 78.7,
      "timeToCollision": 5.15,
      "risk": 33.6,
      "ruleViolation": 22.9,
      "abstention": 15.5,
      "readiness": 75.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-driving-safety-bench/night-crosswalk",
    "bench": "cvpr-driving-safety-bench",
    "page": "cvpr-driving-safety-bench.html",
    "registry": "analysis/cvpr_driving_safety_bench/registry.json",
    "system": "driving-vla-release-gate",
    "cluster": "Driving and vision-language-action",
    "case": "Night crosswalk",
    "family": "safety risk",
    "metric": "risk",
    "metricValue": 31.9,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 75.8,
    "controls": {
      "hazardDensity": 36,
      "actorSpeed": 34,
      "occlusion": 18,
      "actionConfidence": 78
    },
    "metrics": {
      "sceneGrounding": 78.9,
      "timeToCollision": 5.73,
      "risk": 31.9,
      "ruleViolation": 22.8,
      "abstention": 16.0,
      "readiness": 75.8
    },
    "severity": 0
  },
  {
    "id": "cvpr-driving-safety-bench/highway-merge",
    "bench": "cvpr-driving-safety-bench",
    "page": "cvpr-driving-safety-bench.html",
    "registry": "analysis/cvpr_driving_safety_bench/registry.json",
    "system": "driving-vla-release-gate",
    "cluster": "Driving and vision-language-action",
    "case": "Highway merge",
    "family": "safety risk",
    "metric": "risk",
    "metricValue": 34.8,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 74.3,
    "controls": {
      "hazardDensity": 24,
      "actorSpeed": 72,
      "occlusion": 16,
      "actionConfidence": 84
    },
    "metrics": {
      "sceneGrounding": 77.9,
      "timeToCollision": 4.34,
      "risk": 34.8,
      "ruleViolation": 23.9,
      "abstention": 16.0,
      "readiness": 74.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-driving-safety-bench/construction-zone",
    "bench": "cvpr-driving-safety-bench",
    "page": "cvpr-driving-safety-bench.html",
    "registry": "analysis/cvpr_driving_safety_bench/registry.json",
    "system": "driving-vla-release-gate",
    "cluster": "Driving and vision-language-action",
    "case": "Construction zone",
    "family": "safety risk",
    "metric": "risk",
    "metricValue": 32.1,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 75.5,
    "controls": {
      "hazardDensity": 36,
      "actorSpeed": 32,
      "occlusion": 14,
      "actionConfidence": 72
    },
    "metrics": {
      "sceneGrounding": 78.8,
      "timeToCollision": 5.82,
      "risk": 32.1,
      "ruleViolation": 23.0,
      "abstention": 17.3,
      "readiness": 75.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-adversarial-provenance-bench/clean-camera",
    "bench": "cvpr-adversarial-provenance-bench",
    "page": "cvpr-adversarial-provenance-bench.html",
    "registry": "analysis/cvpr_adversarial_provenance_bench/registry.json",
    "system": "adversarial-provenance-gate",
    "cluster": "Adversarial robustness",
    "case": "Clean camera image",
    "family": "provenance gap",
    "metric": "evidence",
    "metricValue": 64.7,
    "threshold": 50,
    "direction": "low",
    "decision": "release",
    "readiness": 76.2,
    "controls": {
      "attackStrength": 0,
      "generationSource": 56,
      "watermarkVisibility": 100,
      "unlearningProbe": 0
    },
    "metrics": {
      "attackCoverage": 3.7,
      "provenanceConfidence": 50.8,
      "leakageRisk": 15.1,
      "evidence": 64.7,
      "risk": 11.6,
      "readiness": 76.2
    },
    "severity": 0
  },
  {
    "id": "cvpr-adversarial-provenance-bench/edited-social-post",
    "bench": "cvpr-adversarial-provenance-bench",
    "page": "cvpr-adversarial-provenance-bench.html",
    "registry": "analysis/cvpr_adversarial_provenance_bench/registry.json",
    "system": "adversarial-provenance-gate",
    "cluster": "Adversarial robustness",
    "case": "Edited social post",
    "family": "provenance gap",
    "metric": "evidence",
    "metricValue": 54.6,
    "threshold": 50,
    "direction": "low",
    "decision": "release",
    "readiness": 66.3,
    "controls": {
      "attackStrength": 0,
      "generationSource": 64,
      "watermarkVisibility": 98,
      "unlearningProbe": 10
    },
    "metrics": {
      "attackCoverage": 2.6,
      "provenanceConfidence": 39.8,
      "leakageRisk": 27.2,
      "evidence": 54.6,
      "risk": 23.7,
      "readiness": 66.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-adversarial-provenance-bench/synthetic-watermarked",
    "bench": "cvpr-adversarial-provenance-bench",
    "page": "cvpr-adversarial-provenance-bench.html",
    "registry": "analysis/cvpr_adversarial_provenance_bench/registry.json",
    "system": "adversarial-provenance-gate",
    "cluster": "Adversarial robustness",
    "case": "Synthetic watermarked media",
    "family": "provenance gap",
    "metric": "evidence",
    "metricValue": 51.3,
    "threshold": 50,
    "direction": "low",
    "decision": "release",
    "readiness": 63.2,
    "controls": {
      "attackStrength": 0,
      "generationSource": 84,
      "watermarkVisibility": 94,
      "unlearningProbe": 44
    },
    "metrics": {
      "attackCoverage": 0.1,
      "provenanceConfidence": 39.1,
      "leakageRisk": 33.2,
      "evidence": 51.3,
      "risk": 29.7,
      "readiness": 63.2
    },
    "severity": 0
  },
  {
    "id": "cvpr-adversarial-provenance-bench/adaptive-attack",
    "bench": "cvpr-adversarial-provenance-bench",
    "page": "cvpr-adversarial-provenance-bench.html",
    "registry": "analysis/cvpr_adversarial_provenance_bench/registry.json",
    "system": "adversarial-provenance-gate",
    "cluster": "Adversarial robustness",
    "case": "Adaptive provenance attack",
    "family": "provenance gap",
    "metric": "evidence",
    "metricValue": 51.2,
    "threshold": 50,
    "direction": "low",
    "decision": "release",
    "readiness": 64.6,
    "controls": {
      "attackStrength": 12,
      "generationSource": 89,
      "watermarkVisibility": 100,
      "unlearningProbe": 0
    },
    "metrics": {
      "attackCoverage": 19.1,
      "provenanceConfidence": 39.9,
      "leakageRisk": 36.2,
      "evidence": 51.2,
      "risk": 32.7,
      "readiness": 64.6
    },
    "severity": 0
  },
  {
    "id": "cvpr-clinical-shift-bench/clear-baseline",
    "bench": "cvpr-clinical-shift-bench",
    "page": "cvpr-clinical-shift-bench.html",
    "registry": "analysis/cvpr_clinical_shift_bench/registry.json",
    "system": "medical-vision-validation",
    "cluster": "Vision for science and medicine",
    "case": "Clear baseline",
    "family": "clinical shift",
    "metric": "residualRisk",
    "metricValue": 2.4,
    "threshold": 50,
    "direction": "high",
    "decision": "release",
    "readiness": 89.9,
    "controls": {
      "scannerShift": 8,
      "cohortMix": 18,
      "labelNoise": 12,
      "reviewThreshold": 68
    },
    "metrics": {
      "shiftLoad": 7.6,
      "calibration": 89.3,
      "domainEvidence": 96.6,
      "triageRate": 68.0,
      "residualRisk": 2.4,
      "clinicalEvidence": 91.6,
      "readiness": 89.9
    },
    "severity": 0
  },
  {
    "id": "cvpr-clinical-shift-bench/scanner-shift",
    "bench": "cvpr-clinical-shift-bench",
    "page": "cvpr-clinical-shift-bench.html",
    "registry": "analysis/cvpr_clinical_shift_bench/registry.json",
    "system": "medical-vision-validation",
    "cluster": "Vision for science and medicine",
    "case": "Scanner shift",
    "family": "clinical shift",
    "metric": "residualRisk",
    "metricValue": 8.9,
    "threshold": 50,
    "direction": "high",
    "decision": "release",
    "readiness": 83.2,
    "controls": {
      "scannerShift": 46,
      "cohortMix": 34,
      "labelNoise": 24,
      "reviewThreshold": 72
    },
    "metrics": {
      "shiftLoad": 32.7,
      "calibration": 91.5,
      "domainEvidence": 85.3,
      "triageRate": 72.0,
      "residualRisk": 8.9,
      "clinicalEvidence": 87.1,
      "readiness": 83.2
    },
    "severity": 0
  },
  {
    "id": "cvpr-clinical-shift-bench/rare-presentation",
    "bench": "cvpr-clinical-shift-bench",
    "page": "cvpr-clinical-shift-bench.html",
    "registry": "analysis/cvpr_clinical_shift_bench/registry.json",
    "system": "medical-vision-validation",
    "cluster": "Vision for science and medicine",
    "case": "Rare presentation",
    "family": "clinical shift",
    "metric": "residualRisk",
    "metricValue": 10.6,
    "threshold": 50,
    "direction": "high",
    "decision": "release",
    "readiness": 81.9,
    "controls": {
      "scannerShift": 58,
      "cohortMix": 52,
      "labelNoise": 18,
      "reviewThreshold": 78
    },
    "metrics": {
      "shiftLoad": 38.0,
      "calibration": 90.7,
      "domainEvidence": 82.9,
      "triageRate": 78.0,
      "residualRisk": 10.6,
      "clinicalEvidence": 85.8,
      "readiness": 81.9
    },
    "severity": 0
  },
  {
    "id": "cvpr-clinical-shift-bench/motion-artifact",
    "bench": "cvpr-clinical-shift-bench",
    "page": "cvpr-clinical-shift-bench.html",
    "registry": "analysis/cvpr_clinical_shift_bench/registry.json",
    "system": "medical-vision-validation",
    "cluster": "Vision for science and medicine",
    "case": "Motion artifact",
    "family": "clinical shift",
    "metric": "residualRisk",
    "metricValue": 11.1,
    "threshold": 50,
    "direction": "high",
    "decision": "release",
    "readiness": 81.1,
    "controls": {
      "scannerShift": 38,
      "cohortMix": 44,
      "labelNoise": 66,
      "reviewThreshold": 74
    },
    "metrics": {
      "shiftLoad": 39.0,
      "calibration": 90.9,
      "domainEvidence": 82.5,
      "triageRate": 74.0,
      "residualRisk": 11.1,
      "clinicalEvidence": 85.3,
      "readiness": 81.1
    },
    "severity": 0
  },
  {
    "id": "cvpr-compute-serving-bench/desktop-batch",
    "bench": "cvpr-compute-serving-bench",
    "page": "cvpr-compute-serving-bench.html",
    "registry": "analysis/cvpr_compute_serving_bench/registry.json",
    "system": "efficient-vision-serving",
    "cluster": "Efficient vision",
    "case": "Desktop batch review",
    "family": "evidence loss",
    "metric": "retainedEvidence",
    "metricValue": 90.9,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 76.6,
    "controls": {
      "tokenBudget": 90,
      "quantizationLevel": 16,
      "studentRouting": 30,
      "escalationCost": 10
    },
    "metrics": {
      "latency": 58.7,
      "retainedEvidence": 90.9,
      "qualityFloor": 87.4,
      "escalationRate": 17.3,
      "costSaving": 38.5,
      "risk": 13.1,
      "readiness": 76.6
    },
    "severity": 0
  },
  {
    "id": "cvpr-compute-serving-bench/mobile-live",
    "bench": "cvpr-compute-serving-bench",
    "page": "cvpr-compute-serving-bench.html",
    "registry": "analysis/cvpr_compute_serving_bench/registry.json",
    "system": "efficient-vision-serving",
    "cluster": "Efficient vision",
    "case": "Mobile live inference",
    "family": "evidence loss",
    "metric": "retainedEvidence",
    "metricValue": 87.5,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 74.6,
    "controls": {
      "tokenBudget": 82,
      "quantizationLevel": 18,
      "studentRouting": 60,
      "escalationCost": 10
    },
    "metrics": {
      "latency": 55.5,
      "retainedEvidence": 87.5,
      "qualityFloor": 81.6,
      "escalationRate": 29.8,
      "costSaving": 45.2,
      "risk": 18.8,
      "readiness": 74.6
    },
    "severity": 0
  },
  {
    "id": "cvpr-compute-serving-bench/edge-camera",
    "bench": "cvpr-compute-serving-bench",
    "page": "cvpr-compute-serving-bench.html",
    "registry": "analysis/cvpr_compute_serving_bench/registry.json",
    "system": "efficient-vision-serving",
    "cluster": "Efficient vision",
    "case": "Edge camera stream",
    "family": "evidence loss",
    "metric": "retainedEvidence",
    "metricValue": 85.7,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 73.5,
    "controls": {
      "tokenBudget": 78,
      "quantizationLevel": 20,
      "studentRouting": 55,
      "escalationCost": 8
    },
    "metrics": {
      "latency": 56.9,
      "retainedEvidence": 85.7,
      "qualityFloor": 81.2,
      "escalationRate": 28.3,
      "costSaving": 44.2,
      "risk": 19.5,
      "readiness": 73.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-compute-serving-bench/fleet-peak-load",
    "bench": "cvpr-compute-serving-bench",
    "page": "cvpr-compute-serving-bench.html",
    "registry": "analysis/cvpr_compute_serving_bench/registry.json",
    "system": "efficient-vision-serving",
    "cluster": "Efficient vision",
    "case": "Fleet peak load",
    "family": "evidence loss",
    "metric": "retainedEvidence",
    "metricValue": 87.6,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 74.6,
    "controls": {
      "tokenBudget": 84,
      "quantizationLevel": 22,
      "studentRouting": 65,
      "escalationCost": 8
    },
    "metrics": {
      "latency": 52.5,
      "retainedEvidence": 87.6,
      "qualityFloor": 80.1,
      "escalationRate": 31.3,
      "costSaving": 48.2,
      "risk": 20.3,
      "readiness": 74.6
    },
    "severity": 0
  },
  {
    "id": "cvpr-long-tail-grounding-bench/common-clean",
    "bench": "cvpr-long-tail-grounding-bench",
    "page": "cvpr-long-tail-grounding-bench.html",
    "registry": "analysis/cvpr_long_tail_grounding_bench/registry.json",
    "system": "open-vocab-visual-search",
    "cluster": "Open-vocabulary vision",
    "case": "Common clean object",
    "family": "localization gap",
    "metric": "localizedEvidence",
    "metricValue": 62.8,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 74.3,
    "controls": {
      "queryRarity": 18,
      "distractorOverlap": 16,
      "boxAmbiguity": 18,
      "evidenceThreshold": 54
    },
    "metrics": {
      "proposalRecall": 74.2,
      "textRegionScore": 26.8,
      "longTailRecall": 39.7,
      "localizedEvidence": 62.8,
      "unsupportedRisk": 21.0,
      "readiness": 74.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-long-tail-grounding-bench/rare-visible",
    "bench": "cvpr-long-tail-grounding-bench",
    "page": "cvpr-long-tail-grounding-bench.html",
    "registry": "analysis/cvpr_long_tail_grounding_bench/registry.json",
    "system": "open-vocab-visual-search",
    "cluster": "Open-vocabulary vision",
    "case": "Rare visible object",
    "family": "localization gap",
    "metric": "localizedEvidence",
    "metricValue": 63.6,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 75.3,
    "controls": {
      "queryRarity": 66,
      "distractorOverlap": 12,
      "boxAmbiguity": 34,
      "evidenceThreshold": 62
    },
    "metrics": {
      "proposalRecall": 75.2,
      "textRegionScore": 26.7,
      "longTailRecall": 43.2,
      "localizedEvidence": 63.6,
      "unsupportedRisk": 21.2,
      "readiness": 75.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-long-tail-grounding-bench/rare-distractors",
    "bench": "cvpr-long-tail-grounding-bench",
    "page": "cvpr-long-tail-grounding-bench.html",
    "registry": "analysis/cvpr_long_tail_grounding_bench/registry.json",
    "system": "open-vocab-visual-search",
    "cluster": "Open-vocabulary vision",
    "case": "Rare object with distractors",
    "family": "localization gap",
    "metric": "localizedEvidence",
    "metricValue": 95.6,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 113.8,
    "controls": {
      "queryRarity": 78,
      "distractorOverlap": 28,
      "boxAmbiguity": 28,
      "evidenceThreshold": 76
    },
    "metrics": {
      "proposalRecall": 79.4,
      "textRegionScore": 93.1,
      "longTailRecall": 85.2,
      "localizedEvidence": 95.6,
      "unsupportedRisk": 8.9,
      "readiness": 113.8
    },
    "severity": 0
  },
  {
    "id": "cvpr-long-tail-grounding-bench/unsupported-query",
    "bench": "cvpr-long-tail-grounding-bench",
    "page": "cvpr-long-tail-grounding-bench.html",
    "registry": "analysis/cvpr_long_tail_grounding_bench/registry.json",
    "system": "open-vocab-visual-search",
    "cluster": "Open-vocabulary vision",
    "case": "Unsupported text query",
    "family": "localization gap",
    "metric": "localizedEvidence",
    "metricValue": 56.0,
    "threshold": 55,
    "direction": "low",
    "decision": "release",
    "readiness": 69.3,
    "controls": {
      "queryRarity": 82,
      "distractorOverlap": 30,
      "boxAmbiguity": 32,
      "evidenceThreshold": 84
    },
    "metrics": {
      "proposalRecall": 60.6,
      "textRegionScore": 17.0,
      "longTailRecall": 40.6,
      "localizedEvidence": 56.0,
      "unsupportedRisk": 23.9,
      "readiness": 69.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-temporal-rollout-bench/short-stable",
    "bench": "cvpr-temporal-rollout-bench",
    "page": "cvpr-temporal-rollout-bench.html",
    "registry": "analysis/cvpr_temporal_rollout_bench/registry.json",
    "system": "video-world-model",
    "cluster": "Video generation and world models",
    "case": "Short stable rollout",
    "family": "temporal drift",
    "metric": "drift",
    "metricValue": 21.0,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 83.3,
    "controls": {
      "rolloutLength": 24,
      "identityDensity": 28,
      "physicsViolations": 14,
      "memoryWindow": 72
    },
    "metrics": {
      "memoryLoad": 26.6,
      "identityStability": 80.6,
      "contactConsistency": 86.6,
      "rolloutPlausibility": 85.7,
      "drift": 21.0,
      "readiness": 83.3
    },
    "severity": 0
  },
  {
    "id": "cvpr-temporal-rollout-bench/crowded-memory",
    "bench": "cvpr-temporal-rollout-bench",
    "page": "cvpr-temporal-rollout-bench.html",
    "registry": "analysis/cvpr_temporal_rollout_bench/registry.json",
    "system": "video-world-model",
    "cluster": "Video generation and world models",
    "case": "Crowded identity memory",
    "family": "temporal drift",
    "metric": "drift",
    "metricValue": 33.0,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 75.9,
    "controls": {
      "rolloutLength": 36,
      "identityDensity": 76,
      "physicsViolations": 26,
      "memoryWindow": 82
    },
    "metrics": {
      "memoryLoad": 43.8,
      "identityStability": 73.8,
      "contactConsistency": 79.4,
      "rolloutPlausibility": 80.0,
      "drift": 33.0,
      "readiness": 75.9
    },
    "severity": 0
  },
  {
    "id": "cvpr-temporal-rollout-bench/contact-heavy",
    "bench": "cvpr-temporal-rollout-bench",
    "page": "cvpr-temporal-rollout-bench.html",
    "registry": "analysis/cvpr_temporal_rollout_bench/registry.json",
    "system": "video-world-model",
    "cluster": "Video generation and world models",
    "case": "Contact-heavy prediction",
    "family": "temporal drift",
    "metric": "drift",
    "metricValue": 34.3,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 76.2,
    "controls": {
      "rolloutLength": 56,
      "identityDensity": 52,
      "physicsViolations": 20,
      "memoryWindow": 82
    },
    "metrics": {
      "memoryLoad": 42.5,
      "identityStability": 74.0,
      "contactConsistency": 83.6,
      "rolloutPlausibility": 77.1,
      "drift": 34.3,
      "readiness": 76.2
    },
    "severity": 0
  },
  {
    "id": "cvpr-temporal-rollout-bench/long-rollout-drift",
    "bench": "cvpr-temporal-rollout-bench",
    "page": "cvpr-temporal-rollout-bench.html",
    "registry": "analysis/cvpr_temporal_rollout_bench/registry.json",
    "system": "video-world-model",
    "cluster": "Video generation and world models",
    "case": "Long rollout drift",
    "family": "temporal drift",
    "metric": "drift",
    "metricValue": 36.1,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 75.9,
    "controls": {
      "rolloutLength": 66,
      "identityDensity": 68,
      "physicsViolations": 12,
      "memoryWindow": 92
    },
    "metrics": {
      "memoryLoad": 48.1,
      "identityStability": 72.7,
      "contactConsistency": 86.5,
      "rolloutPlausibility": 75.5,
      "drift": 36.1,
      "readiness": 75.9
    },
    "severity": 0
  },
  {
    "id": "cvpr-restoration-fidelity-bench/mild-noise",
    "bench": "cvpr-restoration-fidelity-bench",
    "page": "cvpr-restoration-fidelity-bench.html",
    "registry": "analysis/cvpr_restoration_fidelity_bench/registry.json",
    "system": "restoration-reliability-stack",
    "cluster": "Image restoration",
    "case": "Mild sensor noise",
    "family": "fabricated detail",
    "metric": "fabricatedDetailRisk",
    "metricValue": 25.8,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 82.0,
    "controls": {
      "blur": 18,
      "noise": 24,
      "compression": 18,
      "lowLight": 20,
      "hallucinationPenalty": 36
    },
    "metrics": {
      "degradationLoad": 21.6,
      "diagnosisConfidence": 83.8,
      "fidelityScore": 82.2,
      "artifactRisk": 24.7,
      "downstreamUtility": 85.3,
      "fabricatedDetailRisk": 25.8,
      "readiness": 82.0
    },
    "severity": 0
  },
  {
    "id": "cvpr-restoration-fidelity-bench/compressed-low-light",
    "bench": "cvpr-restoration-fidelity-bench",
    "page": "cvpr-restoration-fidelity-bench.html",
    "registry": "analysis/cvpr_restoration_fidelity_bench/registry.json",
    "system": "restoration-reliability-stack",
    "cluster": "Image restoration",
    "case": "Compressed low-light image",
    "family": "fabricated detail",
    "metric": "fabricatedDetailRisk",
    "metricValue": 29.4,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 77.7,
    "controls": {
      "blur": 32,
      "noise": 38,
      "compression": 54,
      "lowLight": 64,
      "hallucinationPenalty": 16
    },
    "metrics": {
      "degradationLoad": 43.6,
      "diagnosisConfidence": 75.7,
      "fidelityScore": 80.3,
      "artifactRisk": 37.4,
      "downstreamUtility": 80.9,
      "fabricatedDetailRisk": 29.4,
      "readiness": 77.7
    },
    "severity": 0
  },
  {
    "id": "cvpr-restoration-fidelity-bench/motion-blur-task",
    "bench": "cvpr-restoration-fidelity-bench",
    "page": "cvpr-restoration-fidelity-bench.html",
    "registry": "analysis/cvpr_restoration_fidelity_bench/registry.json",
    "system": "restoration-reliability-stack",
    "cluster": "Image restoration",
    "case": "Motion blur task frame",
    "family": "fabricated detail",
    "metric": "fabricatedDetailRisk",
    "metricValue": 26.5,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 77.7,
    "controls": {
      "blur": 64,
      "noise": 36,
      "compression": 38,
      "lowLight": 36,
      "hallucinationPenalty": 16
    },
    "metrics": {
      "degradationLoad": 41.2,
      "diagnosisConfidence": 74.2,
      "fidelityScore": 79.0,
      "artifactRisk": 30.4,
      "downstreamUtility": 81.5,
      "fabricatedDetailRisk": 26.5,
      "readiness": 77.7
    },
    "severity": 0
  },
  {
    "id": "cvpr-restoration-fidelity-bench/over-restored-detail",
    "bench": "cvpr-restoration-fidelity-bench",
    "page": "cvpr-restoration-fidelity-bench.html",
    "registry": "analysis/cvpr_restoration_fidelity_bench/registry.json",
    "system": "restoration-reliability-stack",
    "cluster": "Image restoration",
    "case": "Over-restored fine detail",
    "family": "fabricated detail",
    "metric": "fabricatedDetailRisk",
    "metricValue": 28.6,
    "threshold": 42,
    "direction": "high",
    "decision": "release",
    "readiness": 77.8,
    "controls": {
      "blur": 48,
      "noise": 54,
      "compression": 38,
      "lowLight": 56,
      "hallucinationPenalty": 18
    },
    "metrics": {
      "degradationLoad": 45.9,
      "diagnosisConfidence": 75.2,
      "fidelityScore": 80.1,
      "artifactRisk": 35.1,
      "downstreamUtility": 81.2,
      "fabricatedDetailRisk": 28.6,
      "readiness": 77.8
    },
    "severity": 0
  },
  {
    "id": "cvpr-constraint-generation-bench/light-layout-edit",
    "bench": "cvpr-constraint-generation-bench",
    "page": "cvpr-constraint-generation-bench.html",
    "registry": "analysis/cvpr_constraint_generation_bench/registry.json",
    "system": "controllable-generation-studio",
    "cluster": "Controllable generation",
    "case": "Light layout edit",
    "family": "identity damage",
    "metric": "identityDamage",
    "metricValue": 18.5,
    "threshold": 38,
    "direction": "high",
    "decision": "release",
    "readiness": 84.9,
    "controls": {
      "editStrength": 24,
      "layoutLock": 78,
      "identityLock": 82,
      "adversarialPromptPressure": 18
    },
    "metrics": {
      "editPressure": 21.0,
      "constraintSatisfaction": 86.1,
      "identityPreservation": 85.0,
      "editLocality": 82.8,
      "rewardAlignment": 87.3,
      "identityDamage": 18.5,
      "provenanceRisk": 17.6,
      "readiness": 84.9
    },
    "severity": 0
  },
  {
    "id": "cvpr-constraint-generation-bench/style-with-locks",
    "bench": "cvpr-constraint-generation-bench",
    "page": "cvpr-constraint-generation-bench.html",
    "registry": "analysis/cvpr_constraint_generation_bench/registry.json",
    "system": "controllable-generation-studio",
    "cluster": "Controllable generation",
    "case": "Style edit with locks",
    "family": "identity damage",
    "metric": "identityDamage",
    "metricValue": 31.8,
    "threshold": 38,
    "direction": "high",
    "decision": "release",
    "readiness": 77.4,
    "controls": {
      "editStrength": 52,
      "layoutLock": 68,
      "identityLock": 80,
      "adversarialPromptPressure": 32
    },
    "metrics": {
      "editPressure": 39.2,
      "constraintSatisfaction": 80.9,
      "identityPreservation": 77.3,
      "editLocality": 74.4,
      "rewardAlignment": 81.3,
      "identityDamage": 31.8,
      "provenanceRisk": 29.5,
      "readiness": 77.4
    },
    "severity": 0
  },
  {
    "id": "cvpr-constraint-generation-bench/layout-rewrite",
    "bench": "cvpr-constraint-generation-bench",
    "page": "cvpr-constraint-generation-bench.html",
    "registry": "analysis/cvpr_constraint_generation_bench/registry.json",
    "system": "controllable-generation-studio",
    "cluster": "Controllable generation",
    "case": "Aggressive layout rewrite",
    "family": "identity damage",
    "metric": "identityDamage",
    "metricValue": 33.1,
    "threshold": 38,
    "direction": "high",
    "decision": "release",
    "readiness": 77.5,
    "controls": {
      "editStrength": 72,
      "layoutLock": 62,
      "identityLock": 92,
      "adversarialPromptPressure": 28
    },
    "metrics": {
      "editPressure": 45.7,
      "constraintSatisfaction": 81.1,
      "identityPreservation": 78.4,
      "editLocality": 72.9,
      "rewardAlignment": 82.4,
      "identityDamage": 33.1,
      "provenanceRisk": 29.9,
      "readiness": 77.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-constraint-generation-bench/prompt-attack-edit",
    "bench": "cvpr-constraint-generation-bench",
    "page": "cvpr-constraint-generation-bench.html",
    "registry": "analysis/cvpr_constraint_generation_bench/registry.json",
    "system": "controllable-generation-studio",
    "cluster": "Controllable generation",
    "case": "Prompt attack edit",
    "family": "identity damage",
    "metric": "identityDamage",
    "metricValue": 34.8,
    "threshold": 38,
    "direction": "high",
    "decision": "release",
    "readiness": 77.6,
    "controls": {
      "editStrength": 78,
      "layoutLock": 66,
      "identityLock": 92,
      "adversarialPromptPressure": 28
    },
    "metrics": {
      "editPressure": 47.7,
      "constraintSatisfaction": 82.3,
      "identityPreservation": 77.3,
      "editLocality": 73.6,
      "rewardAlignment": 82.5,
      "identityDamage": 34.8,
      "provenanceRisk": 30.0,
      "readiness": 77.6
    },
    "severity": 0
  },
  {
    "id": "cvpr-vlm-answer-verification-bench/visible-count",
    "bench": "cvpr-vlm-answer-verification-bench",
    "page": "cvpr-vlm-answer-verification-bench.html",
    "registry": "analysis/cvpr_vlm_answer_verification_bench/registry.json",
    "system": "vlm-grounded-reasoning",
    "cluster": "Vision-language reasoning",
    "case": "Visible object count",
    "family": "unsupported answer",
    "metric": "unsupportedClaimRisk",
    "metricValue": 11.9,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 77.5,
    "controls": {
      "questionComplexity": 26,
      "priorPressure": 20,
      "toolNeed": 24,
      "evidenceThreshold": 58
    },
    "metrics": {
      "visualCitation": 80.8,
      "toolAgreement": 70.8,
      "contradictionCatch": 71.2,
      "unsupportedClaimRisk": 11.9,
      "readiness": 77.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-vlm-answer-verification-bench/attribute-relation",
    "bench": "cvpr-vlm-answer-verification-bench",
    "page": "cvpr-vlm-answer-verification-bench.html",
    "registry": "analysis/cvpr_vlm_answer_verification_bench/registry.json",
    "system": "vlm-grounded-reasoning",
    "cluster": "Vision-language reasoning",
    "case": "Attribute and relation claim",
    "family": "unsupported answer",
    "metric": "unsupportedClaimRisk",
    "metricValue": 18.0,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 76.8,
    "controls": {
      "questionComplexity": 46,
      "priorPressure": 34,
      "toolNeed": 38,
      "evidenceThreshold": 66
    },
    "metrics": {
      "visualCitation": 78.2,
      "toolAgreement": 72.4,
      "contradictionCatch": 75.3,
      "unsupportedClaimRisk": 18.0,
      "readiness": 76.8
    },
    "severity": 0
  },
  {
    "id": "cvpr-vlm-answer-verification-bench/ocr-trap",
    "bench": "cvpr-vlm-answer-verification-bench",
    "page": "cvpr-vlm-answer-verification-bench.html",
    "registry": "analysis/cvpr_vlm_answer_verification_bench/registry.json",
    "system": "vlm-grounded-reasoning",
    "cluster": "Vision-language reasoning",
    "case": "OCR trap with plausible prior",
    "family": "unsupported answer",
    "metric": "unsupportedClaimRisk",
    "metricValue": 27.1,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 76.8,
    "controls": {
      "questionComplexity": 62,
      "priorPressure": 58,
      "toolNeed": 70,
      "evidenceThreshold": 76
    },
    "metrics": {
      "visualCitation": 74.7,
      "toolAgreement": 77.5,
      "contradictionCatch": 82.0,
      "unsupportedClaimRisk": 27.1,
      "readiness": 76.8
    },
    "severity": 0
  },
  {
    "id": "cvpr-vlm-answer-verification-bench/counterfactual-object",
    "bench": "cvpr-vlm-answer-verification-bench",
    "page": "cvpr-vlm-answer-verification-bench.html",
    "registry": "analysis/cvpr_vlm_answer_verification_bench/registry.json",
    "system": "vlm-grounded-reasoning",
    "cluster": "Vision-language reasoning",
    "case": "Counterfactual unsupported object",
    "family": "unsupported answer",
    "metric": "unsupportedClaimRisk",
    "metricValue": 32.2,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 76.5,
    "controls": {
      "questionComplexity": 78,
      "priorPressure": 72,
      "toolNeed": 82,
      "evidenceThreshold": 84
    },
    "metrics": {
      "visualCitation": 72.5,
      "toolAgreement": 79.2,
      "contradictionCatch": 86.1,
      "unsupportedClaimRisk": 32.2,
      "readiness": 76.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-metric-geometry-bench/wide-baseline",
    "bench": "cvpr-metric-geometry-bench",
    "page": "cvpr-metric-geometry-bench.html",
    "registry": "analysis/cvpr_metric_geometry_bench/registry.json",
    "system": "metric-3d-reconstruction",
    "cluster": "3D reconstruction and novel views",
    "case": "Wide-baseline camera recovery",
    "family": "metric geometry drift",
    "metric": "scaleDrift",
    "metricValue": 10.1,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 85.8,
    "controls": {
      "baseline": 82,
      "textureSparsity": 18,
      "scaleAmbiguity": 24,
      "surfaceComplexity": 42
    },
    "metrics": {
      "poseEvidence": 87.0,
      "metricEvidence": 86.9,
      "surfaceConsistency": 83.1,
      "scaleDrift": 10.1,
      "topologyRisk": 13.9,
      "readiness": 85.8
    },
    "severity": 0
  },
  {
    "id": "cvpr-metric-geometry-bench/scale-transfer",
    "bench": "cvpr-metric-geometry-bench",
    "page": "cvpr-metric-geometry-bench.html",
    "registry": "analysis/cvpr_metric_geometry_bench/registry.json",
    "system": "metric-3d-reconstruction",
    "cluster": "3D reconstruction and novel views",
    "case": "Metric scale transfer",
    "family": "metric geometry drift",
    "metric": "scaleDrift",
    "metricValue": 21.5,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 78.7,
    "controls": {
      "baseline": 66,
      "textureSparsity": 28,
      "scaleAmbiguity": 44,
      "surfaceComplexity": 46
    },
    "metrics": {
      "poseEvidence": 79.2,
      "metricEvidence": 78.8,
      "surfaceConsistency": 78.4,
      "scaleDrift": 21.5,
      "topologyRisk": 21.0,
      "readiness": 78.7
    },
    "severity": 0
  },
  {
    "id": "cvpr-metric-geometry-bench/thin-structure",
    "bench": "cvpr-metric-geometry-bench",
    "page": "cvpr-metric-geometry-bench.html",
    "registry": "analysis/cvpr_metric_geometry_bench/registry.json",
    "system": "metric-3d-reconstruction",
    "cluster": "3D reconstruction and novel views",
    "case": "Thin structure surface check",
    "family": "metric geometry drift",
    "metric": "scaleDrift",
    "metricValue": 22.7,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 75.5,
    "controls": {
      "baseline": 58,
      "textureSparsity": 34,
      "scaleAmbiguity": 32,
      "surfaceComplexity": 72
    },
    "metrics": {
      "poseEvidence": 76.8,
      "metricEvidence": 80.4,
      "surfaceConsistency": 72.5,
      "scaleDrift": 22.7,
      "topologyRisk": 30.0,
      "readiness": 75.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-metric-geometry-bench/low-texture-indoor",
    "bench": "cvpr-metric-geometry-bench",
    "page": "cvpr-metric-geometry-bench.html",
    "registry": "analysis/cvpr_metric_geometry_bench/registry.json",
    "system": "metric-3d-reconstruction",
    "cluster": "3D reconstruction and novel views",
    "case": "Low-texture indoor room",
    "family": "metric geometry drift",
    "metric": "scaleDrift",
    "metricValue": 29.9,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 72.0,
    "controls": {
      "baseline": 54,
      "textureSparsity": 58,
      "scaleAmbiguity": 48,
      "surfaceComplexity": 50
    },
    "metrics": {
      "poseEvidence": 70.1,
      "metricEvidence": 74.7,
      "surfaceConsistency": 72.2,
      "scaleDrift": 29.9,
      "topologyRisk": 30.0,
      "readiness": 72.0
    },
    "severity": 0
  },
  {
    "id": "cvpr-gaussian-splatting-bench/dense-novel-view",
    "bench": "cvpr-gaussian-splatting-bench",
    "page": "cvpr-gaussian-splatting-bench.html",
    "registry": "analysis/cvpr_gaussian_splatting_bench/registry.json",
    "system": "gaussian-splatting-platform",
    "cluster": "Gaussian Splatting",
    "case": "Dense novel-view rendering",
    "family": "splat edit leakage",
    "metric": "editLeakageRisk",
    "metricValue": 16.7,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 85.6,
    "controls": {
      "viewCount": 86,
      "splatDensity": 78,
      "semanticEntropy": 24,
      "provenanceVisibility": 70
    },
    "metrics": {
      "renderFidelity": 86.6,
      "semanticAttachment": 86.4,
      "provenanceTrace": 85.5,
      "viewInstability": 9.4,
      "editLeakageRisk": 16.7,
      "readiness": 85.6
    },
    "severity": 0
  },
  {
    "id": "cvpr-gaussian-splatting-bench/semantic-edit",
    "bench": "cvpr-gaussian-splatting-bench",
    "page": "cvpr-gaussian-splatting-bench.html",
    "registry": "analysis/cvpr_gaussian_splatting_bench/registry.json",
    "system": "gaussian-splatting-platform",
    "cluster": "Gaussian Splatting",
    "case": "Semantic edit selection",
    "family": "splat edit leakage",
    "metric": "editLeakageRisk",
    "metricValue": 21.4,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 82.2,
    "controls": {
      "viewCount": 74,
      "splatDensity": 72,
      "semanticEntropy": 34,
      "provenanceVisibility": 76
    },
    "metrics": {
      "renderFidelity": 81.5,
      "semanticAttachment": 82.4,
      "provenanceTrace": 86.1,
      "viewInstability": 15.7,
      "editLeakageRisk": 21.4,
      "readiness": 82.2
    },
    "severity": 0
  },
  {
    "id": "cvpr-gaussian-splatting-bench/provenance-transfer",
    "bench": "cvpr-gaussian-splatting-bench",
    "page": "cvpr-gaussian-splatting-bench.html",
    "registry": "analysis/cvpr_gaussian_splatting_bench/registry.json",
    "system": "gaussian-splatting-platform",
    "cluster": "Gaussian Splatting",
    "case": "Provenance transfer after edits",
    "family": "splat edit leakage",
    "metric": "editLeakageRisk",
    "metricValue": 24.3,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 80.5,
    "controls": {
      "viewCount": 68,
      "splatDensity": 70,
      "semanticEntropy": 42,
      "provenanceVisibility": 84
    },
    "metrics": {
      "renderFidelity": 78.9,
      "semanticAttachment": 79.8,
      "provenanceTrace": 87.7,
      "viewInstability": 18.8,
      "editLeakageRisk": 24.3,
      "readiness": 80.5
    },
    "severity": 0
  },
  {
    "id": "cvpr-gaussian-splatting-bench/sparse-capture",
    "bench": "cvpr-gaussian-splatting-bench",
    "page": "cvpr-gaussian-splatting-bench.html",
    "registry": "analysis/cvpr_gaussian_splatting_bench/registry.json",
    "system": "gaussian-splatting-platform",
    "cluster": "Gaussian Splatting",
    "case": "Sparse capture with thin geometry",
    "family": "splat edit leakage",
    "metric": "editLeakageRisk",
    "metricValue": 27.4,
    "threshold": 35,
    "direction": "high",
    "decision": "release",
    "readiness": 77.7,
    "controls": {
      "viewCount": 62,
      "splatDensity": 66,
      "semanticEntropy": 46,
      "provenanceVisibility": 72
    },
    "metrics": {
      "renderFidelity": 76.2,
      "semanticAttachment": 77.8,
      "provenanceTrace": 83.8,
      "viewInstability": 23.2,
      "editLeakageRisk": 27.4,
      "readiness": 77.7
    },
    "severity": 0
  }
];
