export const releaseLayers = [
  {
    "id": "coverage-portfolio",
    "status": "coverage-ready",
    "readyStatus": "coverage-ready",
    "page": "cvpr-interactive-coverage-portfolio.html",
    "registry": "analysis/cvpr_interactive_coverage_portfolio/registry.json",
    "package": "source-code/learning/cvpr-interactive-coverage-portfolio",
    "validator": "scripts/verify_cvpr_interactive_coverage_portfolio.py",
    "rowsKey": "portfolioRows",
    "rowCount": 40,
    "pageExists": true,
    "registryExists": true,
    "packageExists": true,
    "validatorExists": true,
    "packageTestExists": true
  },
  {
    "id": "interactive-console",
    "status": "console-ready",
    "readyStatus": "console-ready",
    "page": "cvpr-interactive-console.html",
    "registry": "analysis/cvpr_interactive_console/registry.json",
    "package": "source-code/learning/cvpr-interactive-console",
    "validator": "scripts/verify_cvpr_interactive_console.py",
    "rowsKey": "consoleRows",
    "rowCount": 40,
    "pageExists": true,
    "registryExists": true,
    "packageExists": true,
    "validatorExists": true,
    "packageTestExists": true
  },
  {
    "id": "scenario-runner",
    "status": "runner-ready",
    "readyStatus": "runner-ready",
    "page": "cvpr-interactive-scenario-runner.html",
    "registry": "analysis/cvpr_interactive_scenario_runner/registry.json",
    "package": "source-code/learning/cvpr-interactive-scenario-runner",
    "validator": "scripts/verify_cvpr_interactive_scenario_runner.py",
    "rowsKey": "runnerCases",
    "rowCount": 120,
    "pageExists": true,
    "registryExists": true,
    "packageExists": true,
    "validatorExists": true,
    "packageTestExists": true
  },
  {
    "id": "triage-board",
    "status": "triage-ready",
    "readyStatus": "triage-ready",
    "page": "cvpr-interactive-triage-board.html",
    "registry": "analysis/cvpr_interactive_triage_board/registry.json",
    "package": "source-code/learning/cvpr-interactive-triage-board",
    "validator": "scripts/verify_cvpr_interactive_triage_board.py",
    "rowsKey": "decisionRows",
    "rowCount": 40,
    "pageExists": true,
    "registryExists": true,
    "packageExists": true,
    "validatorExists": true,
    "packageTestExists": true
  }
];
export const summary = {
  "pack": "cvpr-interactive-release-pack",
  "status": "release-pack-ready",
  "layers": 4,
  "readyLayers": 4,
  "pages": 4,
  "registries": 4,
  "packages": 4,
  "validators": 4,
  "packageTests": 4,
  "demos": 40,
  "themes": 8,
  "waves": 5,
  "artifacts": 120,
  "controls": 200,
  "scenarioCases": 120,
  "passingCases": 120,
  "blockedCases": 0,
  "promoteDecisions": 40,
  "monitorDecisions": 0,
  "retestDecisions": 0,
  "holds": 0,
  "validator": "scripts/verify_cvpr_interactive_release_pack.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
