export const reproductionRows = [
  {
    "jobId": "frontier-01-github-com-yjzhao1019-mos",
    "theme": "frontier",
    "repo": "https://github.com/yjzhao1019/MOS",
    "repoName": "MOS",
    "mode": "live-colab",
    "page": "cvpr-frontier-sensor-fusion-bench.html",
    "title": "Frontier Sensor Fusion Reproduction",
    "demoQuestion": "Can the repo evidence support a non-RGB perception demo with provenance and modality-shift checks?",
    "sampleInput": "optical/SAR pair, event burst, or geospatial tile with degraded RGB evidence",
    "expectedOutput": "cross-modal readiness card with artifact link, smoke result, failure probe, and replay command",
    "failureProbe": "sensor mismatch, occlusion, and provenance loss",
    "readiness": 46,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/frontier-01-github-com-yjzhao1019-mos.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job frontier-01-github-com-yjzhao1019-mos",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for MOS.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "threed-01-github-com-deepinsight-insightfa",
    "theme": "threed",
    "repo": "https://github.com/deepinsight/insightface",
    "repoName": "insightface",
    "mode": "live-colab",
    "page": "cvpr-3d-world-repo-arena.html",
    "title": "3D World Reconstruction Reproduction",
    "demoQuestion": "Can the repo evidence support a geometry demo that exposes reconstruction assumptions and failure cases?",
    "sampleInput": "multi-view image set, avatar frame, LiDAR fragment, or 4D scene snippet",
    "expectedOutput": "geometry readiness card with snapshot artifact, runtime gate, and rollback target",
    "failureProbe": "pose drift, missing views, geometry collapse, and identity leakage",
    "readiness": 51,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/threed-01-github-com-deepinsight-insightfa.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job threed-01-github-com-deepinsight-insightfa",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for insightface.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "video-01-github-com-black-forest-labs-flu",
    "theme": "video",
    "repo": "https://github.com/black-forest-labs/flux",
    "repoName": "flux",
    "mode": "live-colab",
    "page": "cvpr-video-temporal-repo-lab.html",
    "title": "Video Temporal Reproduction",
    "demoQuestion": "Can the repo evidence support temporal generation or tracking demos without hiding drift?",
    "sampleInput": "short clip, frame sequence, or prompt-conditioned motion seed",
    "expectedOutput": "temporal output contract with artifact replay, drift probe, and review threshold",
    "failureProbe": "long-horizon drift, identity swap, hallucinated motion, and dropped objects",
    "readiness": 47,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/video-01-github-com-black-forest-labs-flu.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job video-01-github-com-black-forest-labs-flu",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for flux.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "generation-01-github-com-joyies-gdpo",
    "theme": "generation",
    "repo": "https://github.com/Joyies/GDPO",
    "repoName": "GDPO",
    "mode": "live-colab",
    "page": "cvpr-generation-control-repo-studio.html",
    "title": "Generation Control Reproduction",
    "demoQuestion": "Can the repo evidence support a controllable generation demo with measurable constraints?",
    "sampleInput": "prompt, degraded image, restoration target, or preference-control request",
    "expectedOutput": "generation comparison panel with constraint status, artifact trace, and promotion decision",
    "failureProbe": "prompt leakage, over-smoothing, restoration hallucination, and reward gaming",
    "readiness": 37,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-01-github-com-joyies-gdpo",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for GDPO.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "vlm-01-github-com-chao2433-fedafd",
    "theme": "vlm",
    "repo": "https://github.com/Chao2433/FedAFD",
    "repoName": "FedAFD",
    "mode": "live-colab",
    "page": "cvpr-grounded-vlm-repo-court.html",
    "title": "Grounded VLM Reproduction",
    "demoQuestion": "Can the repo evidence support grounded answer checks instead of unverified captions?",
    "sampleInput": "image plus question, retrieval context, graph prompt, or privacy-sensitive visual evidence",
    "expectedOutput": "answer/evidence verdict with source artifact, grounding notes, and escalation gate",
    "failureProbe": "ungrounded answer, private attribute leak, graph shortcut, and retrieval mismatch",
    "readiness": 46,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/vlm-01-github-com-chao2433-fedafd.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job vlm-01-github-com-chao2433-fedafd",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for FedAFD.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "perception-01-github-com-primebo1-fob",
    "theme": "perception",
    "repo": "https://github.com/primebo1/FoB",
    "repoName": "FoB",
    "mode": "live-colab",
    "page": "cvpr-perception-parts-repo-bench.html",
    "title": "Perception Parts Reproduction",
    "demoQuestion": "Can the repo evidence support part, mask, or detection demos on difficult visual regimes?",
    "sampleInput": "open-vocabulary scene, panoramic frame, camouflaged object, or few-shot support set",
    "expectedOutput": "mask/detection readiness panel with artifact-backed smoke result and failure tag",
    "failureProbe": "small object miss, class synonym drift, pseudo-label collapse, and occlusion",
    "readiness": 51,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/perception-01-github-com-primebo1-fob.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job perception-01-github-com-primebo1-fob",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for FoB.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "embodied-01-github-com-szu-ai-safe-driving-d",
    "theme": "embodied",
    "repo": "https://github.com/szu-ai/safe-driving-drl",
    "repoName": "safe-driving-drl",
    "mode": "live-colab",
    "page": "cvpr-embodied-control-repo-drill.html",
    "title": "Embodied Control Reproduction",
    "demoQuestion": "Can the repo evidence support an action demo that exposes policy safety and recovery?",
    "sampleInput": "driving scene, GUI task, manipulation state, or visual RL observation",
    "expectedOutput": "policy readiness card with action trace, artifact evidence, and safety review path",
    "failureProbe": "unsafe action, reward shortcut, recovery failure, and scene distribution shift",
    "readiness": 57,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/embodied-01-github-com-szu-ai-safe-driving-d.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job embodied-01-github-com-szu-ai-safe-driving-d",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for safe-driving-drl.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  },
  {
    "jobId": "learning-01-github-com-eit-nlp-embedlens",
    "theme": "learning",
    "repo": "https://github.com/EIT-NLP/EmbedLens",
    "repoName": "EmbedLens",
    "mode": "live-colab",
    "page": "cvpr-efficient-learning-repo-governor.html",
    "title": "Efficient Learning Reproduction",
    "demoQuestion": "Can the repo evidence support an efficiency demo that preserves quality under compression or adaptation?",
    "sampleInput": "few-shot batch, continual stream, pruning target, or token budget",
    "expectedOutput": "cost/quality tradeoff card with promoted artifact, runtime gate, and rollback path",
    "failureProbe": "quality cliff, adaptation drift, memory blow-up, and stale calibration",
    "readiness": 57,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.json",
    "smokeJson": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.json",
    "log": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.log",
    "repoSnapshot": "source-code/learning/cvpr-repo-gpu-harness/_results/learning-01-github-com-eit-nlp-embedlens.snapshot.json",
    "artifactsComplete": true,
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job learning-01-github-com-eit-nlp-embedlens",
    "nextImplementation": "Build cached output viewer, input selector, artifact diff, failure probe, and promotion notes for EmbedLens.",
    "reproductionScore": 100,
    "decision": "build-interactive-demo"
  }
];
export const summary = {
  "track": "cvpr-paper-reproduction-track",
  "status": "track-ready",
  "commandStatus": "operator-ready",
  "manifestStatus": "manifest-ready",
  "sourcePromotedResults": "analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json",
  "sourceCommandCenter": "analysis/cvpr_live_evidence_command_center/registry.json",
  "sourceManifest": "analysis/cvpr_live_evidence_release_manifest/registry.json",
  "reproductions": 8,
  "themes": 8,
  "liveRows": 8,
  "smokePassed": 8,
  "artifactsComplete": 8,
  "interactive": 8,
  "cached": 0,
  "needsReproPass": 0,
  "hold": 0,
  "minReproductionScore": 100,
  "validator": "scripts/validate_cvpr_repo_harness_results.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
