"""Stage and optionally promote a live CVPR Colab GPU export."""
import argparse
import json
from pathlib import Path

from validate_cvpr_colab_results import DEFAULT_MANIFEST, DEFAULT_RESULTS, load_json, validate

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_EXPORT = ROOT / "source-code/learning/cvpr-colab-gpu-worker/_incoming/cvpr_gpu_results_live.json"
DEFAULT_REPORT = ROOT / "analysis/cvpr_colab_live_intake/registry.json"
DEFAULT_PAGE = ROOT / "cvpr-colab-live-intake.html"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def esc(value):
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def build_page(report, export_path, canonical_path, promoted):
    summary = report["summary"]
    rows = "".join(
        f"""<tr><td>{esc(job['jobId'])}</td><td>{job['expectedCases']}</td><td>{job['actualCases']}</td><td>{'ready' if job['ready'] else 'blocked'}</td></tr>"""
        for job in report["jobs"]
    )
    issue_rows = "".join(
        f"""<tr><td>{esc(issue.get('type'))}</td><td>{esc(issue.get('jobId', ''))}</td><td>{esc(issue)}</td></tr>"""
        for issue in report["issues"]
    ) or """<tr><td>none</td><td></td><td>all live Colab cases passed intake</td></tr>"""
    page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CVPR Colab Live Intake</title>
<style>:root{{--ink:#101719;--paper:#F5F6F4;--panel:#FBFCFB;--line:#D7DCD9;--muted:#59656A;--accent:#0E7C86;--mono:ui-monospace,"SF Mono",Menlo,Consolas,monospace;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,Arial,sans-serif}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);line-height:1.5}}.wrap{{max-width:1120px;margin:0 auto;padding:0 24px}}header{{background:var(--ink);color:#E7ECED;padding:42px 0 34px}}.bug,nav a,.stat span,th,code{{font-family:var(--mono)}}.bug{{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#4FC4CE}}h1{{font-size:44px;line-height:1.04;margin:10px 0}}header p{{max-width:84ch;color:#AEBABD}}nav a{{font-size:12px;color:#B7DDE1;margin-right:12px}}.stats{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}}.stat,.panel{{background:var(--panel);border:1px solid var(--line);border-radius:8px}}.stat{{padding:13px}}.stat b{{display:block;font-size:28px}}.stat span{{font-size:11px;color:var(--muted)}}.panel{{padding:16px;margin:18px 0}}table{{width:100%;border-collapse:collapse;font-size:13px}}td,th{{border-bottom:1px solid var(--line);padding:8px;text-align:left;vertical-align:top}}th{{font-size:11px;color:var(--muted)}}code{{display:block;background:#EEF3F2;padding:10px;border-radius:6px;white-space:normal}}footer{{border-top:1px solid var(--line);padding:20px 0 54px;color:var(--muted);font-family:var(--mono);font-size:12px}}@media(max-width:900px){{.stats{{grid-template-columns:1fr 1fr}}}}</style></head>
<body><header><div class="wrap"><div class="bug">CVPR 2026 · live Colab intake</div><h1>CVPR Colab Live Intake</h1><p>Validation and promotion gate for replacing cached GPU evidence with a live Google Colab Pro+ export.</p><nav><a href="cvpr-colab-gpu-worker.html">worker</a><a href="cvpr-colab-release-bundle.html">release bundle</a><a href="analysis/cvpr_colab_live_intake/registry.json">registry</a></nav></div></header>
<main class="wrap"><section class="stats"><article class="stat"><b>{esc(summary['status'])}</b><span>intake status</span></article><article class="stat"><b>{summary['actualResults']}</b><span>live results</span></article><article class="stat"><b>{summary['validJobs']}</b><span>valid jobs</span></article><article class="stat"><b>{summary['issues']}</b><span>issues</span></article></section>
<section class="panel"><h2>Promotion Command</h2><code>python3 scripts/stage_cvpr_live_colab_export.py --export source-code/learning/cvpr-colab-gpu-worker/_incoming/cvpr_gpu_results_live.json --promote</code><code>last checked export: {esc(export_path)}</code><code>canonical artifact: {esc(canonical_path)}</code><code>promoted: {esc(promoted)}</code></section>
<section class="panel"><h2>Job Intake</h2><table><thead><tr><th>Job</th><th>Expected</th><th>Actual</th><th>Status</th></tr></thead><tbody>{rows}</tbody></table></section>
<section class="panel"><h2>Issues</h2><table><thead><tr><th>Type</th><th>Job</th><th>Detail</th></tr></thead><tbody>{issue_rows}</tbody></table></section></main>
<footer><div class="wrap">Generated by scripts/stage_cvpr_live_colab_export.py · canonical artifact remains source-code/learning/cvpr-colab-gpu-worker/_results/cvpr_gpu_results.json</div></footer></body></html>"""
    write(DEFAULT_PAGE, page)


def canonicalize_live_results(results):
    canonical = []
    for result in results:
        row = dict(result)
        row["mode"] = "cached-real"
        row["provenance"] = {
            **result.get("provenance", {}),
            "promotedFrom": "live-colab",
            "canonicalMode": "cached-real",
        }
        canonical.append(row)
    return canonical


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default=DEFAULT_MANIFEST)
    parser.add_argument("--export", default=DEFAULT_EXPORT)
    parser.add_argument("--report", default=DEFAULT_REPORT)
    parser.add_argument("--canonical-results", default=DEFAULT_RESULTS)
    parser.add_argument("--promote", action="store_true", help="Replace the canonical GPU results after a clean live intake.")
    args = parser.parse_args()

    export_path = Path(args.export)
    canonical_path = Path(args.canonical_results)
    live_results = load_json(export_path)
    report = validate(load_json(args.manifest), live_results, expected_mode="live-colab")
    summary = report["summary"]
    promoted = False

    if args.promote:
        if summary["status"] != "valid":
            raise SystemExit("refusing to promote invalid live Colab export")
        canonical_path.parent.mkdir(parents=True, exist_ok=True)
        if canonical_path.exists():
            backup = canonical_path.with_suffix(".cached-real.backup.json")
            backup.write_text(canonical_path.read_text(encoding="utf-8"), encoding="utf-8")
        canonical_path.write_text(json.dumps(canonicalize_live_results(live_results), indent=2) + "\n", encoding="utf-8")
        promoted = True

    canonical_display = str(canonical_path.relative_to(ROOT) if canonical_path.is_absolute() and canonical_path.is_relative_to(ROOT) else canonical_path)
    output = {
        "summary": {
            **summary,
            "intake": "cvpr-colab-live-intake",
            "export": str(export_path.relative_to(ROOT) if export_path.is_absolute() and export_path.is_relative_to(ROOT) else export_path),
            "canonicalArtifact": canonical_display,
            "promoted": promoted,
        },
        "jobs": report["jobs"],
        "issues": report["issues"],
    }
    report_path = Path(args.report)
    write(report_path, json.dumps(output, indent=2) + "\n")
    build_page(output, output["summary"]["export"], canonical_display, promoted)
    print(
        f"staged CVPR live Colab export: {summary['actualResults']} results, "
        f"{summary['issues']} issues, promoted {promoted}"
    )
    raise SystemExit(0 if summary["status"] == "valid" else 1)


if __name__ == "__main__":
    main()
