"""Verify the CVPR demo next-build playbook."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "analysis/cvpr_demo_playbook/registry.json"


def main():
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    arena = json.loads((ROOT / "analysis/cvpr_demo_arena/registry.json").read_text(encoding="utf-8"))
    summary = data["summary"]
    assert summary["plays"] == len(arena["recommendations"])
    assert summary["sourceDemos"] == arena["summary"]["demos"]
    assert summary["sourceScenarios"] == arena["summary"]["scenarios"]
    assert summary["sourcePairings"] == arena["summary"]["pairings"]
    assert summary["clustersCovered"] >= 8
    assert summary["scenariosCovered"] >= 6
    assert summary["critical"] >= 0
    assert summary["complete"] == summary["plays"]
    assert summary["incomplete"] == 0
    for play in data["plays"]:
        assert play["targetReadiness"] >= min(68, play["currentReadiness"])
        assert len(play["deliverables"]) >= 4
        assert play["controlSurface"]
        assert play["instrumentation"]
        assert play["acceptanceGate"]
        assert play["arenaFinding"]
    implemented_pages = {play["implementationPage"] for play in data["plays"]}
    assert {
        "cvpr-driving-safety-bench.html",
        "cvpr-adversarial-provenance-bench.html",
        "cvpr-clinical-shift-bench.html",
        "cvpr-compute-serving-bench.html",
        "cvpr-long-tail-grounding-bench.html",
    }.issubset(implemented_pages)
    page = (ROOT / "cvpr-demo-playbook.html").read_text(encoding="utf-8")
    for token in (
        "Turn weak demo scenarios into buildable goals",
        "Execution Order",
        "Acceptance gate",
        "cvpr-driving-safety-bench.html",
        "cvpr-adversarial-provenance-bench.html",
        "cvpr-clinical-shift-bench.html",
        "cvpr-compute-serving-bench.html",
        "cvpr-long-tail-grounding-bench.html",
        "Generated by scripts/build_cvpr_demo_playbook.py",
    ):
        assert token in page
    assert "cvpr-demo-playbook.html" in (ROOT / "index.html").read_text(encoding="utf-8")
    assert "cvpr-demo-playbook.html" in (ROOT / "cvpr-demo-arena.html").read_text(encoding="utf-8")
    assert (ROOT / "source-code/learning/cvpr-demo-playbook/src/core.js").exists()
    assert (ROOT / "source-code/learning/cvpr-demo-playbook/src/plays.js").exists()
    assert (ROOT / "source-code/learning/cvpr-demo-playbook/tests/core.test.js").exists()
    print(
        f"verified CVPR demo playbook: {summary['plays']} plays, "
        f"{summary['critical']} critical, {summary['clustersCovered']} clusters"
    )


if __name__ == "__main__":
    main()
