export const stages = [
  {
    "system": "adversarial-provenance-gate",
    "systemTitle": "Adversarial provenance gate",
    "stage": "attack-surface",
    "stageTitle": "Map attack surface",
    "theme": "The frontier - new senses and new duties",
    "themeSlug": "emerging",
    "cluster": "Adversarial robustness",
    "clusterSlug": "adversarial",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "test corruptions, prompts, generated media, and sensor shifts",
    "reusableRule": "Adversarial provenance gate stage 'Map attack surface' should test corruptions, prompts, generated media, and sensor shifts using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "adversarial-provenance-gate",
    "systemTitle": "Adversarial provenance gate",
    "stage": "provenance-detection",
    "stageTitle": "Detect provenance",
    "theme": "The frontier - new senses and new duties",
    "themeSlug": "emerging",
    "cluster": "Adversarial robustness",
    "clusterSlug": "adversarial",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "separate real, edited, generated, and watermarked media",
    "reusableRule": "Adversarial provenance gate stage 'Detect provenance' should separate real, edited, generated, and watermarked media using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "adversarial-provenance-gate",
    "systemTitle": "Adversarial provenance gate",
    "stage": "unlearning-check",
    "stageTitle": "Check unlearning",
    "theme": "The frontier - new senses and new duties",
    "themeSlug": "emerging",
    "cluster": "Adversarial robustness",
    "clusterSlug": "adversarial",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "prove removed concepts do not leak back through shortcuts",
    "reusableRule": "Adversarial provenance gate stage 'Check unlearning' should prove removed concepts do not leak back through shortcuts using measured CVPR evidence, not only paper novelty."
  }
];
