export const studioRows = [
  {
    "jobId": "generation-01-github-com-joyies-gdpo",
    "caseId": "cvpr-generation-control-repo-studio-1",
    "scenario": "One-step SR texture evidence replay",
    "repo": "https://github.com/Joyies/GDPO",
    "mode": "live-colab",
    "page": "cvpr-generation-control-repo-studio.html",
    "paperTitle": "GDPO-SR: Group Direct Preference Optimization for One-Step Generative Image Super-Resolution",
    "baseDecision": "block",
    "artifactRisk": 72.1,
    "liveReadiness": 37,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-01-github-com-joyies-gdpo.json",
    "artifactQuestion": "Does the promoted run provide enough repo evidence to inspect whether one-step SR sharpens texture without inventing structure?",
    "artifactProbe": "texture hallucination under one-step super-resolution",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-01-github-com-joyies-gdpo",
    "evidenceScore": 98.5,
    "decision": "artifact-review"
  },
  {
    "jobId": "generation-02-github-com-chanson94-codsr",
    "caseId": "cvpr-generation-control-repo-studio-2",
    "scenario": "Controllable restoration fidelity replay",
    "repo": "https://github.com/Chanson94/CODSR",
    "mode": "live-colab",
    "page": "cvpr-generation-control-repo-studio.html",
    "paperTitle": "Bridging Fidelity-Reality with Controllable One-Step Diffusion for Image Super-Resolution",
    "baseDecision": "block",
    "artifactRisk": 78.1,
    "liveReadiness": 34,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-02-github-com-chanson94-codsr.json",
    "artifactQuestion": "Does the live artifact support fidelity versus perceptual realism checks for controllable SR?",
    "artifactProbe": "fidelity-realism tradeoff under restoration controls",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-02-github-com-chanson94-codsr",
    "evidenceScore": 94.4,
    "decision": "artifact-review"
  },
  {
    "jobId": "generation-03-github-com-gyr02-nadb",
    "caseId": "cvpr-generation-control-repo-studio-3",
    "scenario": "Diffusion bridge endpoint replay",
    "repo": "https://github.com/gyr02/NADB",
    "mode": "live-colab",
    "page": "cvpr-generation-control-repo-studio.html",
    "paperTitle": "Resolving Endpoint Underfitting in Diffusion Bridges via Noise Alignment",
    "baseDecision": "block",
    "artifactRisk": 69.2,
    "liveReadiness": 40,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-03-github-com-gyr02-nadb.json",
    "artifactQuestion": "Does the promoted result carry enough evidence to inspect endpoint correction in a diffusion bridge?",
    "artifactProbe": "endpoint drift across diffusion bridge correction",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-03-github-com-gyr02-nadb",
    "evidenceScore": 100,
    "decision": "artifact-review"
  },
  {
    "jobId": "generation-04-github-com-jf-tan-lrdm",
    "caseId": "cvpr-generation-control-repo-studio-4",
    "scenario": "Low-rank residual repair replay",
    "repo": "https://github.com/JF-Tan/LRDM",
    "mode": "live-colab",
    "page": "cvpr-generation-control-repo-studio.html",
    "paperTitle": "Low-Rank Residual Diffusion Models",
    "baseDecision": "block",
    "artifactRisk": 70.1,
    "liveReadiness": 38,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-04-github-com-jf-tan-lrdm.json",
    "artifactQuestion": "Does the live row support checking whether residual diffusion repairs only the intended residual?",
    "artifactProbe": "local edit leakage under low-rank residual repair",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-04-github-com-jf-tan-lrdm",
    "evidenceScore": 99.8,
    "decision": "artifact-review"
  },
  {
    "jobId": "generation-05-github-com-mililab-rdbm",
    "caseId": "cvpr-generation-control-repo-studio-5",
    "scenario": "Universal restoration repaint replay",
    "repo": "https://github.com/MiliLab/RDBM",
    "mode": "live-colab",
    "page": "cvpr-generation-control-repo-studio.html",
    "paperTitle": "Residual Diffusion Bridge Model for Image Restoration",
    "baseDecision": "block",
    "artifactRisk": 75.5,
    "liveReadiness": 33,
    "smokePassed": true,
    "runtimeSeconds": 0.0,
    "accelerator": "A100",
    "evidenceArtifact": "source-code/learning/cvpr-repo-gpu-harness/_results/generation-05-github-com-mililab-rdbm.json",
    "artifactQuestion": "Does the promoted artifact support checks that universal restoration avoids repainting already-clean regions?",
    "artifactProbe": "over-restoration and clean-region repainting",
    "replayCommand": "python3 scripts/validate_cvpr_repo_harness_results.py --results analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json --job generation-05-github-com-mililab-rdbm",
    "evidenceScore": 93.8,
    "decision": "artifact-review"
  }
];
export const summary = {
  "studio": "cvpr-generation-control-live-evidence-studio",
  "status": "ready",
  "theme": "generation",
  "rows": 5,
  "liveRows": 5,
  "smokePassed": 5,
  "artifacts": 5,
  "promoteDemo": 0,
  "artifactReview": 5,
  "holdDemo": 0,
  "minEvidenceScore": 93.8,
  "maxArtifactRisk": 78.1,
  "sourceGenerationStudio": "analysis/cvpr_generation_control_repo_studio/registry.json",
  "sourceCommandCenter": "analysis/cvpr_repo_harness_command_center/registry.json",
  "sourcePromotedResults": "analysis/cvpr_repo_harness_replacement_receipt/cvpr_repo_harness_results.promoted.json",
  "validator": "scripts/validate_cvpr_repo_harness_results.py",
  "fullStackCommand": "python3 scripts/validate_cvpr_full_stack.py"
};
