export const stages = [
  {
    "system": "restoration-reliability-stack",
    "systemTitle": "Restoration reliability stack",
    "stage": "degradation-diagnosis",
    "stageTitle": "Diagnose degradation",
    "theme": "Making pixels from meaning",
    "themeSlug": "generation",
    "cluster": "Image restoration",
    "clusterSlug": "restoration",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "separate blur, noise, compression, low light, and sensor artifacts",
    "reusableRule": "Restoration reliability stack stage 'Diagnose degradation' should separate blur, noise, compression, low light, and sensor artifacts using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "restoration-reliability-stack",
    "systemTitle": "Restoration reliability stack",
    "stage": "fidelity-gate",
    "stageTitle": "Gate restoration fidelity",
    "theme": "Making pixels from meaning",
    "themeSlug": "generation",
    "cluster": "Image restoration",
    "clusterSlug": "restoration",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "restore visible evidence without fabricating task-critical details",
    "reusableRule": "Restoration reliability stack stage 'Gate restoration fidelity' should restore visible evidence without fabricating task-critical details using measured CVPR evidence, not only paper novelty."
  },
  {
    "system": "restoration-reliability-stack",
    "systemTitle": "Restoration reliability stack",
    "stage": "downstream-validation",
    "stageTitle": "Validate downstream utility",
    "theme": "Making pixels from meaning",
    "themeSlug": "generation",
    "cluster": "Image restoration",
    "clusterSlug": "restoration",
    "themePaperCount": 0,
    "clusterPaperCount": 0,
    "gateScore": 94,
    "residualRiskPct": 10,
    "evidenceDepthScore": 94,
    "decision": "pass",
    "releaseRule": "prove restored images improve the target task, not just aesthetics",
    "reusableRule": "Restoration reliability stack stage 'Validate downstream utility' should prove restored images improve the target task, not just aesthetics using measured CVPR evidence, not only paper novelty."
  }
];
